### ISSUE TITLE
There's a lotta bug to the update 7.4...

### ISSUE THREAD

**Issue by memereb** [KotatsuApp/Kotatsu#1003]
### Brief summary

After i updated my Kotatsu to version 7.4; these things happened.

On a site at the first picture, as you can see that's it's problem.. Please fix it, code-related.

At the second however, i've written about it... Please fix it.

![Screenshot_20240731_110602](https://github.com/user-attachments/assets/dfba80ec-c23b-43de-b43b-74ceb42dc8b2)
![Screenshot_20240731_082417](https://github.com/user-attachments/assets/3fdb0f8d-c1ed-4dcc-a002-b6246f486670)

### Kotatsu version

7.4

### Android version

Any

### Device

Any

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
