### ISSUE TITLE
Wrong estimated reading time

### ISSUE THREAD

**Issue by Mhuzaifakhalid** [KotatsuApp/Kotatsu#1017]
### Brief summary

I dont know on what basis the estimated reading time is given. But it is absolutely wrong everytime. I think it works on the basis that an average chapter take about 1-2 minutes. So it multiples that by the total chapters, which isn't a good method to do so. Firstly,  its different for manhwas and mangas. Secondly the first chapter of most titles are way longer, also there is the option to read in volumes in mangafire and mangareader which is substantially more. 

The right approach to this would be to take the number of the chapters (without loading them if this is possible) and multiplying them by an average time taken to read one (something around 5 to 10 seconds.) Or having the feature to learn how much time an individual takes to read a single page to find it out. 

### Steps to reproduce

Open any big title from any source to check it

### Kotatsu version

7.4.1

### Android version

14

### Device

Samsung s21FE

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
Because the code contains average values of reading time per page and number of pages per chapter. Magic Numbers. Someday there will be a time calculation based on how the user reads and everyone will have a unique one
