### ISSUE TITLE
Update notice still persists

### ISSUE THREAD

**Issue by RandomParacodes** [KotatsuApp/Kotatsu#1032]
### Brief summary

After updating the app, the update indicator is still shown.
![Screenshot_20240813-010635_Kotatsu](https://github.com/user-attachments/assets/899e75bb-1767-4f57-ae98-a9781638b26d)
![Screenshot_20240813-010640_Kotatsu](https://github.com/user-attachments/assets/91083c41-270c-4198-9b48-d1893f69aac9)

### Steps to reproduce

1. Update to 7.4.2
2. Wait
3. Force stop the app just to make sure
4. Update indicator still shows.

### Kotatsu version

7.4.2

### Android version

13

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by k557osuman** [comment]
yo same problem here

**Comment by Mhuzaifakhalid** [comment]
Here as well

**Comment by Betinhahxhd** [comment]
Alguém fez? Deu certo?
