### ISSUE TITLE
Add a new source

### ISSUE THREAD

**Issue by Kurumii-ii** [KotatsuApp/Kotatsu#1038]
### Describe your suggested feature

Would it be possible to add this source into kotatsu
The source website : https://hitomi.la

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by MariusAlbrecht** [comment]
The issue template clearly states that this repo is the wrong place for this kind of issue.
It's definitely possible to add this source.
Someone will have to do the work though.

**Comment by Kurumii-ii** [comment]
Mb i didnt see that
