### ISSUE TITLE
Won't update 

### ISSUE THREAD

**Issue by Andrei3432-coder** [KotatsuApp/Kotatsu#1044]
### Brief summary

I press update and I would download after I press open . I open the app and it still says that I have to update. And for some time I don't receive notifications about new chapters and don't see new chapters 

### Steps to reproduce

I pres update. I wait it to download. I press open and when I open the app it still says I need to update 

### Kotatsu version

7.4.2

### Android version

10

### Device

Xiaomi redmi 9 T

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Andrei3432-coder** [comment]
Can you help me?

**Comment by ztimms73** [comment]
Duplicate of #1032
