### ISSUE TITLE
Hide nsfw

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/Kotatsu#1057]
### Describe your suggested feature

please add hide nsfw feature on on device tab

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ErickaEc** [comment]
What do you mean by that?
Could you please?

**Comment by diecko69** [comment]
on the downloaded manga added a filter to hide manga in the nsfw category

Pada Sab, 24 Agu 2024 09.37, ErickaEc ***@***.***> menulis:

> What do you mean by that?
> Could you please?
>

**Comment by kernnnn** [comment]
How is the logic implemented? Just wondering as nsfw works tagged as ecchi and 18+ still show up, even though nsfw is already disabled in the settings.

**Comment by Koitharu** [comment]
It depends on manga source
