### ISSUE TITLE
sourceBug

### ISSUE THREAD

**Issue by AyanokojiThong77** [KotatsuApp/Kotatsu#1059]
### Brief summary

![Screenshot_2024-08-27-19-47-09-355_org koitharu kotatsu](https://github.com/user-attachments/assets/6e7cce75-d34a-4d09-9b60-27192c2ce039)

### Kotatsu version

7.4.2

### Android version

11

### Device

Redmi k60

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
