### ISSUE TITLE
Grayscale doesnt work

### ISSUE THREAD

**Issue by Kurumii-ii** [KotatsuApp/Kotatsu#1065]
### Brief summary

Grayscale feature in color correction settings doesnt work, the settings wont save

### Steps to reproduce

1. Read any manga
2. Long press and go into color correction settings
3. Turn on grayscale
4. Save it only for that manga
5. The settings is not saved

### Kotatsu version

7.4.3

### Android version

14

### Device

Mi 11 Lite 5G NE

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment]
can confirm.
For me it doesn't get applied at all though, it isn't only not being saved.

**Comment by Kurumii-ii** [comment]
> can confirm. For me it doesn't get applied at all though, it isn't only not being saved.

Same here
