### ISSUE TITLE
Unable To Read Downloaded Manga Without Internet Connection 

### ISSUE THREAD

**Issue by Kurumii-ii** [KotatsuApp/Kotatsu#1071]
### Brief summary

I used to be able to read downloaded manga without internet connection but after updating to version 7.5, i m unable to do that now

### Steps to reproduce

1. Download any mangas
2. Turn off ur internet connection
3. Read the downloaded manga
4. Unable to read the managa as kotatsu shows connection error

![Screenshot_2024-09-03-20-43-04-285_org koitharu kotatsu](https://github.com/user-attachments/assets/64e63d89-2d45-4a68-a51f-4323f40693e3)

![Screenshot_2024-09-03-20-43-09-653_org koitharu kotatsu](https://github.com/user-attachments/assets/e8e7c547-5ff6-44fd-a55b-13d25f854bf2)

### Kotatsu version

7.5

### Android version

14

### Device

Xiaomi 11 Lite 5G NE

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Blehbleher** [comment]
there is a workaround,open it in incognito

**Comment by Kurumii-ii** [comment]
> there is a workaround,open it in incognito

Thx
