### ISSUE TITLE
All the sources cant be open

### ISSUE THREAD

**Issue by Dreadedmacaroni** [KotatsuApp/Kotatsu#1074]
### Brief summary

As I open the sources, all of it says invalid proxy configuration and this happens after I just updated the app
![Screenshot_20240903_215132_Kotatsu](https://github.com/user-attachments/assets/0e854ea9-d029-43f8-a873-cef9069533fd)
![Screenshot_20240903_215746_Kotatsu](https://github.com/user-attachments/assets/5483a57e-1cde-49aa-9286-9746f01a4865)

### Steps to reproduce

Open the app, and pick any sources since you can't even read any chapters since it says "no chapter"
![Screenshot_20240903_215957_Kotatsu](https://github.com/user-attachments/assets/0045757b-38a9-4bd8-99dc-57000ae671d1)
![Screenshot_20240903_220007_Kotatsu](https://github.com/user-attachments/assets/2344847a-0d06-4215-bbb7-1b7ce3ed209f)

### Kotatsu version

7.5

### Android version

Android 13

### Device

Samsung Galaxy a12

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Check for your proxy settings

**Comment by Dreadedmacaroni** [comment]
![Screenshot_20240904_080800_Kotatsu](https://github.com/user-attachments/assets/54a215a1-4ea7-4c7c-8da5-4bc83d796c88)

**Comment by Koitharu** [comment]
Change type to None

**Comment by Dreadedmacaroni** [comment]
Thank you

**Comment by GiulianoVenturo** [comment]
Same problem after updating. I follow the step to change Type to none and now my app opens but close after 2 seconds. Any idea what could it be? 

Thank you
