### ISSUE TITLE
Quick filter issue

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/Kotatsu#1079]
### Brief summary

For the quick filter in the on device section, it only displays downloaded manga.

### Kotatsu version

7.5

### Android version

13.0

### Device

Redmi Note 8 pro

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
And what is the issue?

**Comment by diecko69** [comment]
Only showing some manga, not all. Sorry I use a translator and don't double check the results

**Comment by diecko69** [comment]
for example i have 5 manga on tab favorites,but only shows 3 manga

**Comment by MariusAlbrecht** [comment]
the "on device" filter is supposed to display only offline-accessible chapters (i.e downloaded ones). If not all of your favourites are downloaded, then not all of them will get shown in that filter.

**Comment by diecko69** [comment]
I mean, all the manga I downloaded only show a few

Pada Rab, 4 Sep 2024 20.07, Marius Albrecht ***@***.***>
menulis:
