### ISSUE TITLE
network error on downloaded chapters

### ISSUE THREAD

**Issue by jeidojzed08** [KotatsuApp/Kotatsu#1081]
### Brief summary

i cant read the downloaded chapters after i turn off my wifi, it says network error even downloaded already

### Kotatsu version

7.5

### Android version

5.0

### Device

samsung j1

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Blehbleher** [comment]
a workaround at the moment is opening them in incognito for the time being
