### ISSUE TITLE
Can't read offline

### ISSUE THREAD

**Issue by 4issue** [KotatsuApp/Kotatsu#1082]
### Brief summary

cant read Downloaded chapters offline and Network Issue pops up. Only holding down the "Continue" button then going incognito mode works. thanks to power outage lol

### Steps to reproduce

1. Download any manga chapters
2. turn off wifi/data
3. try opening downloaded chapters

### Kotatsu version

7.5

### Android version

12

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment]
I was able to reproduce this issue on 7.4.
I wanted to do a screen recording but now I can no longer reproduce the same issue after updating to 7.5.

Can you provide more detailed steps to reproduce?

**Comment by apacheit2** [comment]
same issue here.... waiting for new update

**Comment by apacheit2** [comment]
> I was able to reproduce this issue on 7.4. I wanted to do a screen recording but now I can no longer reproduce the same issue after updating to 7.5.
> 
> Can you provide more detailed steps to reproduce?
> 
> The description of your issue also isn't 100% clear to me: Does the chapter get displayed or does nothing get displayed? What's the "Continue" button you're talking about? On my device a network error has one button which is labelled with "Close" and not "Continue".
> 
> does `download -> turn off network access -> turn on incognito mode -> open downloaded chapter` work?

https://github.com/user-attachments/assets/40e26f18-58d1-44e4-8998-e25c1eed3288


here's the video on what he means

**Comment by Ero-gamer** [comment]
I have the same issue, it seem this bug is introduced in v7.5. I never had this issue before using Kotatsu previous versions for months. Also app crash after 5 sec when chapters auto updates + suggestions updates notification show up, I had to downgrade to v7.4.3 to disable auto updates to use v7.5 only to get another offline reading bug.

![Screenshot_2024-09-05-00-04-15-23](https://github.com/user-attachments/assets/9d616c6c-63c9-45f8-8a30-fbd47dd84f19)

**Comment by MariusAlbrecht** [comment]
@Ero-gamer 7.5.1 should fix this.

**Comment by Ero-gamer** [comment]
> @Ero-gamer 7.5.1 should fix this.

Offline reading bug is fixed but crash bug due to updates notification still remain.

**Comment by MariusAlbrecht** [comment]
> > @Ero-gamer 7.5.1 should fix this.
> 
> Offline reading bug is fixed but crash bug due to updates notification still remain.

There's been a second update (7.5.2.), maybe that fixed the other problem as well?

anyway, crashes seem to be off-topic for this specific issue. Iirc there already is at least one issue for the crashes. If so, follow that, else feel free to open a new issue if the problem persists.

**Comment by MrChocolatine** [comment]
@Koitharu @MariusAlbrecht 

To this day, I don't consider this issue being fixed.
Whenever I download chapters and goes offline (Aeroplane mode), the app does not let me read the said chapters.

### How to reproduce 

- Open Kotatsu
- Download chapters for a certain manga
- Close Kotatsu
- Activate "Aeroplane mode" on Android
- Open Kotatsu
- Select the same previous manga
- Click the `Continue` button (which should renders `Read Loading...`)
- Nothing renders apart from a spinner
- Go back to the main page of the manga
- Slide up the `Chapters` section
- The list of chapters renders nothing apart from a spinner

### Recording

https://github.com/user-attachments/assets/9b71dbf8-43d9-41c5-b87f-10280dfee864

### My setup

- Kotatsu: version 7.5.2
- Android: version 14

**Comment by MariusAlbrecht** [comment]
> - Open Kotatsu
> - Download chapters for a certain manga
> - Close Kotatsu
> - Activate "Aeroplane mode" on Android
> - Open Kotatsu
> - Select the same previous manga
> - Click the `Continue` button (which should renders `Read Loading...`)

I don't see a 'Continue' button here

> - Nothing renders apart from a spinner
> - Go back to the main page of the manga
> - Slide up the `Chapters` section
> - The list of chapters renders nothing apart from a spinner

For me the list shows exactly what I expect it to: my downloaded chapters

**Comment by MrChocolatine** [comment]
> I don't see a 'Continue' button here

What I meant by that, and you can see from my recording, the large button that is supposed to say `Continue`.

> For me the list shows exactly what I expect it to: my downloaded chapters

Any other way trying to resolve/work this out apart from "it works for me"?

**Comment by MrChocolatine** [comment]
Something I should also mention, a workaround I have found is to reboot my phone.
Which is more than annoying as you can imagine.
