### ISSUE TITLE
captcha deactivation

### ISSUE THREAD

**Issue by sunsivaraj** [KotatsuApp/Kotatsu#1084]
### Describe your suggested feature

please add a captcha deactivation button  in the parameter, i always get  5 to 10 bad captcha notification in the notification bar. even if i deactivate the updates.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
You can turn off notifications about captcha in the system notifications settings

**Comment by sunsivaraj** [comment]
hi thanks that worked, but can't we deactivate the captcha verification ?

**Comment by Koitharu** [comment]
Captcha verification is initiated by the website, so no
