### ISSUE TITLE
Option to roll back to previous app version

### ISSUE THREAD

**Issue by sonnenfell** [KotatsuApp/Kotatsu#1085]
### Describe your suggested feature

It would be great if there was an option to roll back to the previous version of the app.

Something like a "Roll back to previous version" button in the "About" (aka app version) section which allows you to "undo" the last update (maybe even with a confirmation window warning you that you'll lose access to the latest features until you update again).

I got the idea for this feature because version 7.5 didn't allow me to normally read my downloaded mangas without internet connection, which is one of the most important features to me. There is a workaround, but I think having the choice to simply roll back one version just in case something similar were to happen again could be a crucial factor in deciding app reader to use and an improvement to the overall stability of the app.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
It is impossible because of Android restrictions

Wait for 7.5.1, it will bring fixes for these issues. Sorry for that
