### ISSUE TITLE
Automotic update via Droid-Ify

### ISSUE THREAD

**Issue by authorless** [KotatsuApp/Kotatsu#1091]
### Describe your suggested feature

Hello, your new versions are not displayed in the sources F-Droid. 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
F-droid have some delays for building new versions
