### ISSUE TITLE
Error entering an extension 

### ISSUE THREAD

**Issue by Okami321** [KotatsuApp/Kotatsu#1096]
### Brief summary

When I try to enter DragonsTranslation (Spanish) I get failed and I don't know if you can fix it, thanks 
![Screenshot_2024-09-10-03-05-21-858_org koitharu kotatsu](https://github.com/user-attachments/assets/a46b9214-ddd6-4232-9d87-95895e48396c)
![Screenshot_2024-09-10-03-05-13-339_org koitharu kotatsu](https://github.com/user-attachments/assets/f9fd65e4-a853-4ea1-b01b-2a8b455eadf8)

### Kotatsu version

7.5.2

### Android version

14

### Device

Redmi Note 13 4G 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment]
please show the details of the error and please navigate to the manga on their website in your normal browser to see if that works.

**Comment by Okami321** [comment]
![Screenshot_2024-09-10-22-41-11-164_com android chrome-edit](https://github.com/user-attachments/assets/9499e019-93ef-49c5-a7a9-a0fd7eaccb5a)
![Screenshot_2024-09-10-22-42-26-772_org koitharu kotatsu](https://github.com/user-attachments/assets/11126484-3130-499e-a5e8-4d60f30d15e4)

There is this in the app I get that error and on the website it works normally.

**Comment by Okami321** [comment]
![Screenshot_2024-09-10-22-49-02-318_com android chrome](https://github.com/user-attachments/assets/404737dd-60c7-4946-a3cb-d853d7ecd18e)
![Screenshot_2024-09-10-22-49-07-690_org koitharu kotatsu](https://github.com/user-attachments/assets/b8e7736b-cb7a-4610-b419-15a586eea814)

Even here I have an error when entering an extension

**Comment by Okami321** [comment]
So how do I fix it?
