### ISSUE TITLE
Search option for favourites

### ISSUE THREAD

**Issue by FeeninForMore** [KotatsuApp/Kotatsu#1098]
### Describe your suggested feature

Can we maybe get a search option for your favourites? Like I have way too many planned manga and I wanna search through them

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Mhuzaifakhalid** [comment]
+1 upvote
Makes sense, if I search in the search bar, it shows that manga from all the available sources. 
![Screenshot_20240915_185402_Kotatsu](https://github.com/user-attachments/assets/8465b481-e3d6-4365-aec2-fd8a278c3e18)
It should have a seperate space just for searching amongst the favourites.

**Comment by Firmen-net** [comment]
totally agree

**Comment by NA0341** [comment]
Suggestion for two search result view types:
+ Sort results by favorite category and name (display category names like the inline sections in Settings (the colored text)
+ Sort results by name and display the favorite category on each item.

**Comment by 45thhokage** [comment]
Don't we have this? Shouldn't this be closed now
