### ISSUE TITLE
Error occurred with Arabic sources 

### ISSUE THREAD

**Issue by NIMSIS-W** [KotatsuApp/Kotatsu#1104]
### Brief summary

Hey dev team, 

-I am facing and error occurred while trying to open any manga related to [](https://lekmanga.net) 
-Version : 7.5.2.
-Problem is about source (**specially Arabic sources**).
- I am facing this while I am trying to open any manga.
- Problem is consistent.
- 

### Kotatsu version

7.5.2

### Android version

14

### Device

oneplus 12R

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
