### ISSUE TITLE
Cant find downloaded chapters after update

### ISSUE THREAD

**Issue by Chris-455** [KotatsuApp/Kotatsu#1115]
### Brief summary

After update to 7.6 the local storage only shows  Invalid End header(bad central directory) 

### Kotatsu version

7.6

### Android version

10

### Device

Samsung Note 9

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
> shows Invalid End header(bad central directory)

More details (screenshot)?
