### ISSUE TITLE
ePub Support

### ISSUE THREAD

**Issue by varud** [KotatsuApp/Kotatsu#1119]
### Describe your suggested feature

This is the most beautiful and user-friendly manga reader I've found on Android. 
I'm wondering if there are any plans to add support for local EPUB files in the future? I enjoy reading both manga and novels, and having a single app that can handle both would be fantastic.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
Not planned
