### ISSUE TITLE
French sources say error

### ISSUE THREAD

**Issue by Adhelaiide** [KotatsuApp/Kotatsu#1128]
### Brief summary

Most French sources say there is a server error even though they work perfectly in the browser

### Steps to reproduce

 The sources is : mangascnatrad.io/epsilonscan.to/epsilon soft.to/ravenscan/frscan/bentoscan 

![Screenshot_20241006-235042](https://github.com/user-attachments/assets/b6f47fa1-5c43-4657-9dca-850c0c45de3e)
![Screenshot_20241006-235048](https://github.com/user-attachments/assets/48105d55-c716-4cb2-b42e-e2983506cd4b)
![Screenshot_20241006-235059](https://github.com/user-attachments/assets/13bc998d-9196-4bee-9186-a8ed105a0834)
![Screenshot_20241006-235119](https://github.com/user-attachments/assets/2d5e1999-8524-405f-9be6-db4920c9aaad)
![Screenshot_20241006-235202](https://github.com/user-attachments/assets/bcb1922b-0864-4592-81dd-c31f8c713803)
![Screenshot_20241006-234511](https://github.com/user-attachments/assets/64e6d1d4-7b55-4178-8435-874624ddb40e)
![Screenshot_20241006-235630](https://github.com/user-attachments/assets/c71abaac-ac60-4230-9a3f-399b88fcbf1d)
![Screenshot_20241006-235635](https://github.com/user-attachments/assets/55f27a1c-23c8-465a-957e-6720dff42cbf)

### Kotatsu version

7.6.2

### Android version

Android 10

### Device

Techno spark 4 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).
