### ISSUE TITLE
App cloning 

### ISSUE THREAD

**Issue by 45thhokage** [KotatsuApp/Kotatsu#1132]
### Describe your suggested feature

I'm not sure what would have to be needed but I would the ability to clone the app. I currently have two devices with essentially two different profiles (reading different types of manga/manhwa). I want to keep both profiles separated but I sometimes want read what's on another phone when it's charging etc. I tried using lucky patcher and all the green and yellow patches failed
![Screenshot_2024-10-08-02-38-40-86_8ecc2a44d2cdc6522cb76f61cfe7f43c](https://github.com/user-attachments/assets/6b12b555-4c01-4760-8ac1-0e12624857a1)

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment]
Fork it, change package name and build it

**Comment by Kisbivaly** [comment]
Create two diferent favorites and use one for one of the device
