### ISSUE TITLE
The chapter doesn't open

### ISSUE THREAD

**Issue by TheKingOmar** [KotatsuApp/Kotatsu#1134]
### Brief summary

Whenever I try to open a chapter from some sources it says " content unavailable or removed" I tried opening it via browser and it worked perfectly, so I am not sure what's causing this issue

### Steps to reproduce

1. Open manga
2. Try to open chapter
3. Get message that says "content unavailable or removed"

### Kotatsu version

7.6.4

### Android version

12

### Device

Xiaomi note 12 pro+

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment]
I assume there's a lot of necessary information missing here.
My app works fine for lots of comics from lots of sources.

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
