### ISSUE TITLE
Add avif image support

### ISSUE THREAD

**Issue by SilentNN** [KotatsuApp/Kotatsu#1138]
### Describe your suggested feature

Add support for avif image files such as the ones the ReaperComics source uses.

Example of chapter with image format: https://reaperscans.com/series/player-who-returned-10000-years-later-824/chapter-96
Issue opened in parser repo: https://github.com/KotatsuApp/kotatsu-parsers/issues/1035

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by MariusAlbrecht** [comment]
should be in the update.
