### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [KotatsuApp/Kotatsu#1152]
### Brief summary

```
> Task :app:minifyReleaseWithR8 FAILED
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/vagrant/build/org.koitharu.kotatsu/app/build/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class coil3.PlatformContext (referenced from: coil3.network.ConnectivityChecker coil3.network.okhttp.OkHttpNetworkFetcher$OkHttpNetworkFetcherFactory$6.invoke(coil3.PlatformContext) and 1 other context)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete
```

https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8183101698 Could you please take a look? Thanks!

### Kotatsu version

7.7-a3

### Android version

14

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by dragonx943** [comment]
> ### Brief summary
> ```
> > Task :app:minifyReleaseWithR8 FAILED
> ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/vagrant/build/org.koitharu.kotatsu/app/build/outputs/mapping/release/missing_rules.txt.
> ERROR: R8: Missing class coil3.PlatformContext (referenced from: coil3.network.ConnectivityChecker coil3.network.okhttp.OkHttpNetworkFetcher$OkHttpNetworkFetcherFactory$6.invoke(coil3.PlatformContext) and 1 other context)
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:minifyReleaseWithR8'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
>    > Compilation failed to complete
> ```
> 
> https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8183101698 Could you please take a look? Thanks!
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> 7.7-a3
> 
> ### Android version
> 14
> 
> ### Device
> _No response_
> 
> ### Acknowledgements
> * [x]  This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
> * [x]  This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

if u want v7.7-a3, u can visit my repo :p

**Comment by Koitharu** [comment]
F-Droid builds alpha? O_o

**Comment by dragonx943** [comment]
> F-Droid builds alpha? O_o

never heard of it before :p

**Comment by Koitharu** [comment]
This issue was already fixed

**Comment by linsui** [comment]
Thanks! 7.6.5 and 7.6.6 tags have wrong version name and version code. Could you please fix them?
