### ISSUE TITLE
Webtoon music

### ISSUE THREAD

**Issue by Fuzzythegoatq** [KotatsuApp/Kotatsu#1176]
### Describe your suggested feature

Kotatsu but we have the feature to turn on that webtoon music while reading on the webtoon source. 

Example: 
 
https://m.webtoons.com/en/comedy/99-reinforced-wooden-stick/s2-ep-11-gallardo-the-gargantuan-dragon-2/viewer?title_no=4286&episode_no=98

Also can the webtoons.com and Webtoons.com Translations sources be added. Would make the app way better

18+: Nah

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by dragonx943** [comment]
> ### Describe your suggested feature
> Kotatsu but we have the feature to turn on that webtoon music while reading on the webtoon sourcd.
> 
> ### Acknowledgements
> * [x]  This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

like ur phone can only open one app at a time :V

**Comment by MariusAlbrecht** [comment]
> Also can the webtoons.com and Webtoons.com Translations sources be added. Would make the app way better

wrong place. post here https://github.com/KotatsuApp/kotatsu-parsers

**Comment by ztimms73** [comment]
This is far too niche to justify adding non-trivial audio support.
