### ISSUE TITLE
The shinigami manga source problem 

### ISSUE THREAD

**Issue by Boqirz213** [KotatsuApp/Kotatsu#1201]
### Brief summary

When first activating the Shinigami manga source, the displayed website address is the old one, not the new one. After changing the address to the latest one, issues arise when trying to read the selected manga, manhua, or manhwa, as no chapters are available. Additionally, this manga source requires solving a captcha issue, but when attempting to fix it on the external website, access is blocked.
![Screenshot_20241206-024118](https://github.com/user-attachments/assets/3f9a2ba8-c2c1-4079-9083-c352469e89b5)
![Screenshot_20241206-024140](https://github.com/user-attachments/assets/caa0388a-9fb5-450a-bb0f-e0f5a66fb6f6)
![Screenshot_20241206-024131](https://github.com/user-attachments/assets/2889c90e-1c0e-4dfa-9e3f-b6e4404aa9c6)
![Screenshot_20241206-025142](https://github.com/user-attachments/assets/a557cabb-9b0c-4c51-889f-6c9686b3c3a9)
![Screenshot_20241206-022737](https://github.com/user-attachments/assets/194cd32c-3020-4e3a-928d-c916d78b8f9a)
![Screenshot_20241206-022642](https://github.com/user-attachments/assets/197bf5ab-6df7-40c3-abf6-9b77de2b7147)

### Steps to reproduce

1.Launch the Kotatsu application.
2.Activate the Shinigami manga source.
3.Notice that the website address is outdated and not the latest one.
4.Go to settings and update the website address to the latest version.
5.Select any manga, manhwa, or manhua to read.
6.Observe that no chapters are available or displayed.
7.Attempt to access the application via an external web browser.
8.Note the access block message.

### Kotatsu version

7.7

### Android version

11.0

### Device

Infinix hot 11 play

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment]
> - [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Boqirz213** [comment]
> > * [x]  This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

Alright sorry

**Comment by Boqirz213** [comment]
Sorry
