### ISSUE TITLE
More favorite options 

### ISSUE THREAD

**Issue by Yashgfdufdr** [KotatsuApp/Kotatsu#1204]
### Describe your suggested feature

Their should be more options like droped, plan to read and on hold and all this should also set Proggress on mal and anilist

Also favorites should be renamed to categories and another favorite list should be made which would like droped, plan to read, last read and on hold where you can put your actual favorite content 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Yashgfdufdr** [comment]
To add to this i would also like if history was able to be opned without putting it on home screen. 

It can be put on Threedots

**Comment by Yashgfdufdr** [comment]
And a final request content which can be should automatically be traked on anilist and mal or atleast give us a option to enable this and if app doesn't find the content it should basically give inapp notification of not finding it.

**Comment by Koitharu** [comment]
You can add any custom categories of favorites 

> Their should be more options like droped, plan to read and on hold

**Comment by Ulol-04** [comment]
bro explore the app omfg, everything your suggesting is already in the app
