### ISSUE TITLE
about source's 

### ISSUE THREAD

**Issue by 77amza** [KotatsuApp/Kotatsu#1208]
### Describe your suggested feature

hi everyone iam really thankful of your work guys and i hope you guys can add something so we can add a sources by our selves because i speak arabic and i cant find enough source's to read from and thank you <3

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment]
https://kotatsu.app/dev/contribute/#parsers-contribution-guidelines
