### ISSUE TITLE
New Chapter Detection 

### ISSUE THREAD

**Issue by Mhuzaifakhalid** [KotatsuApp/Kotatsu#1212]
### Brief summary

It's happening with me for months now. I use Mangafire as my primary source and have added many favourites from it. But the app doesn't detect new chapters for some titles. These are the favourites:

https://github.com/user-attachments/assets/eb970f48-0cff-4358-bc32-cdfadc9d84ef

But the weirdest thing is it happens only with mangas, not manhwas, as in the feed section attached below. I have been getting notification for new chapters for every single one of my manhwas but not any manga (but kagurabachi is an exception for some reason and makes this even more complex)

https://github.com/user-attachments/assets/c20ba7ec-ca3a-4c56-84a0-c197fb45a29c

The app does check for new chapters when i refresh by doesnt detect it. When i open a manga after a week, there will be a new chapter but it NEVER detects that. The logs:

https://github.com/user-attachments/assets/80c6dc03-888f-4c04-a529-ac332d95563a

I opened this issue 4 months ago in the parser page but it was closed. I don't know if it's an app or parser issue but it's really bothers me. 

### Kotatsu version

7.7.2

### Android version

14

### Device

Samsung s22 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Mhuzaifakhalid** [comment]
Please look into it

**Comment by Avetisiana** [comment]
@Koitharu Sorry I'm new to this, but how do you update the code for the fix on the phone ? I am on the latest version of the app and  have this bug after changing phones and restoring my backup a few days ago.
