### ISSUE TITLE
Sometimes, when you use multiple "save page", it starts to save previous page.

### ISSUE THREAD

**Issue by EdgE790** [KotatsuApp/Kotatsu#165]
### Steps to reproduce

1. Open some manga chapter.
1. Save multiple different pages.
3. (??? not sure if needed) go to another chapter.
4. Try to save the page.

### Expected behavior

A page that is currently on screen will be saved.

### Actual behavior

Some previous page is saved, that is not currently displayed on screen.

### Kotatsu version

3.2.1

### Android version

Android 11

### Device

vivo 1920

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2.1](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by EdgE790** [comment]
May contain not all necessary information but #164 makes testing harder, because it necessary to add extension to all saved files before they can be reviewd.

**Comment by ztimms73** [comment]
Looks like closed #38

**Comment by nv95** [comment]
Close?

**Comment by EdgE790** [comment]
Just tested on 3.4.6.
It's working for me, thank you.
