### ISSUE TITLE
Support For Anilist

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/Kotatsu#177]
### Describe your suggested feature

Please add Anilist feature like saikou where we can check the manga which i have completed, current, paused,etc. And after clicking on the specific manga it should produce search from all the sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.3](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
We will think about Anilist integration after we deal with Shikimori first
