### ISSUE TITLE
Ongoing - Finished

### ISSUE THREAD

**Issue by yephny** [KotatsuApp/Kotatsu#186]
For the source MangaRead, it says Berserk is finished, although it is ongoing. I believe it was marked as finished after the mangaka died a year ago. However, it is currently ongoing, but it's not updated on Kotatsu. I'm not sure if it's caused by Kotatsu or the source itself. Could it be that Kotatsu doesn't check whether a manga's finished or not once it's been marked as Finished?

**Comment by ztimms73** [comment]
The status of the manga will be displayed in the application the same as that indicated on the site. It all depends on the administration of the site, which was given this status. Kotatsu developers are not directly related to the sites, so all questions are directed to them.
