### ISSUE TITLE
Last Visited menu

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/Kotatsu#190]
### Describe your suggested feature

Hii please add function so that the app can be launched from last visited menu Tab as it get sometimes annoying always opening favourite tab.

### Kotatsu version

3.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new).
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
Hii bro you can move your favorites category to the first position and then it will always be open at startup

**Comment by OshekharO** [comment]
> Hii bro you can move your favorites category to the first position and then it will always be open at startup

Alright but ya please make one wiki mentioning these things because without knowing about it how can I know that this also existed

**Comment by OshekharO** [comment]
> Hii bro you can move your favorites category to the first position and then it will always be open at startup

![Screenshot_2022-07-01-22-36-06-60_a5af3585a93e2016f6667aaf7e1e2f32](https://user-images.githubusercontent.com/95137948/176939485-175969e4-c1bd-40f9-9875-6c00ce14f87f.jpg)

No it's not working and there is no option to move those sections item up and down. They have default settings.

**Comment by OshekharO** [comment]
For example i have closed the App after reading manga from ninemanga. Then later on when I again open the app it should automatically select ninemanga tab instead of favourite tab.

**Comment by OshekharO** [comment]
> > tabs
> 
> I thought about tabs in favourites screen. Menus in navigation view are called menus

Alright, then any solution for this or should I close this issue?

**Comment by ztimms73** [comment]
There no solution, also don't close this issue, maybe we implement this stuff

**Comment by Koitharu** [comment]
No more actual due to ui changes
