### ISSUE TITLE
Misrendering while switching pages zoomed

### ISSUE THREAD

**Issue by qirlib** [KotatsuApp/Kotatsu#193]
### Steps to reproduce

Zoom in on a manga page n. Not depressing your finger from the screen, scroll far enough to see a bit of the page n+1; then move your finger backwards to the original position.

### Expected behavior

You observe pages n and n+1.

### Actual behavior

You observe pages n, n+1 and n-1.

### Kotatsu version

3.3.2

### Android version

Android 11

### Device

Uh. No.

### Other details

P. S. Through, admittedly, I didn't see lots of them, this is probably the most disrespectful bug report form I've seen, both to my and your intelligences. You're not exactly Minecraft in size to have average expected submission quality this low to justify having this. "When zoomed, scrolling past the border to another page and back causes misrendering with another page appearing." sentence sums it up nicely and is the only thing I should have written and is the only thing one should be expected to write.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new).
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
Thanks for the feedback about issue template. We think it's normal. So the more data from user about issue = the better. Or not according to you?

Back to issue. I can't reproduce it.

**Comment by qirlib** [comment]
It's not about the amount of information the user can provide, it's about "we will close and ignore your issue if we don't like it", bonus for precommitment required: "I will fill out all of the requested information in this form." Given my bug report is a short sentence, I almost gave up filing it upon reading this. A better approach to this I've seen is "Please, please do provide the following information: ... , remove this comment to acknowledge you've read through it.", no strict adherence required. Just as you, the users don't have an unlimited amount of time and have a tradeoff of spending time on this or other things. Filtering out some bug reports from your input is not in your interests, is it?

Here's the video:
https://user-images.githubusercontent.com/10223503/177327947-56b10087-a00c-40b0-9b28-24bcf700a3d5.mp4

**Comment by ztimms73** [comment]
> "we will close and ignore your issue if we don't like it"

We are not hypocrites and this has never been and will never be.

> "I will fill out all of the requested information in this form."

Check issue #55. Here is a vivid example of why we need to collect as much information as possible from the user in order to understand what problem the user is facing.

> users don't have an unlimited amount of time and have a tradeoff of spending time

I'm sorry, but it's necessary. If you don't like collecting information about the problem from the user and it takes SO much time, then don't create issues. For sane users, filling out a issue template usually does not cause problems.

**Comment by qirlib** [comment]
Bug report form controversy discussion moved [here](https://github.com/KotatsuApp/Kotatsu/discussions/198).
