### ISSUE TITLE
3 line manga names cut off "add to favorite" button

### ISSUE THREAD

**Issue by GoluLiliput** [KotatsuApp/Kotatsu#197]
### Steps to reproduce

1. Open any source
2. Open any 3 or 4 liner title name manga (long-ass names)

### Expected behavior

The "Add to Favorites" button shouldn't be cropped out

### Actual behavior

The "Add to Favorites" button is cropped out
![Screenshot_20220706-190219_Kotatsu](https://user-images.githubusercontent.com/60719832/177563918-089f79e4-fae7-40f6-b224-4ba2363c0638.jpg)
![Screenshot_20220706-190244_Kotatsu](https://user-images.githubusercontent.com/60719832/177563933-6297495c-6780-40b2-83b6-232341d06554.jpg)
![Screenshot_20220706-190310_Kotatsu](https://user-images.githubusercontent.com/60719832/177563941-87059e08-15a9-4e9b-bbbe-b77f9b194db9.jpg)

### Kotatsu version

3.4

### Android version

Android 12

### Device

Samsung Galaxy Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new).
- [X] I will fill out all of the requested information in this form.

**Comment by nv95** [comment]
Thank you for report, fixed
