### ISSUE TITLE
a question ?

### ISSUE THREAD

**Issue by N0tvich** [KotatsuApp/Kotatsu#199]
### Describe your suggested feature

I would like to know if they are going to add more content in Spanish

### Kotatsu version

"3.4"

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new).
- [ ] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
What are you meaning? Spanish soucres?
