### ISSUE TITLE
Add Lazy Mode and slider

### ISSUE THREAD

**Issue by meanindra** [KotatsuApp/Kotatsu#204]
### Describe your suggested feature

Can you add this two feature lazy mode and slider.
Lazy mode like Infinity have https://github.com/Docile-Alligator/Infinity-For-Reddit
![Screenshot_20220717-000754_Infinity](https://user-images.githubusercontent.com/36324543/179367998-7284f3cc-d631-47a6-8e56-96ec50f44fb3.png)
And Sliding like LibreraReader have
https://github.com/foobnix/LibreraReader
![Screenshot_20220717-001308_Librera_PRO](https://user-images.githubusercontent.com/36324543/179368115-f60109d8-88e4-4e29-8793-6376b721356e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by nv95** [comment]
Lazy mode is automatic page switching/scroll in the reader, right?

**Comment by meanindra** [comment]
> Lazy mode is an automatic page switching/scrolling in the reader, right?

yes

**Comment by ztimms73** [comment]
Check 4.0-alpha1
