### ISSUE TITLE
MyAnimeList, Anilist and Kitsu integration

### ISSUE THREAD

**Issue by Gliscor** [KotatsuApp/Kotatsu#208]
### Describe your suggested feature

MyAnimeList, Anilist and Kitsu are manga and anime trackers, would be nice to have integration and sync your reads with these services too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by kyoyacchi** [comment]
and MangaUpdates would be good, too

**Comment by killerlearner** [comment]
If only myanimelist can be integrated that will be great also

**Comment by Gliscor** [comment]
Hast his been considered? @Koitharu

**Comment by ztimms73** [comment]
Work in progress @Gliscor
