### ISSUE TITLE
Сортировка в разделе "На устройстве"

### ISSUE THREAD

**Issue by qvazzar** [KotatsuApp/Kotatsu#217]
### Describe your suggested feature

Добавить сортировку в раздел скачанной манги. Как минимум, нужна сортировка по дате скачивания и названию, а также возможно по количеству страниц и источнику загрузки. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Done, available in v4
