### ISSUE TITLE
Add the ability to sort local imports alphabetical/etc

### ISSUE THREAD

**Issue by Rowsinator** [KotatsuApp/Kotatsu#219]
### Describe your suggested feature

As of right now, unless I'm missing an obsure setting, the local import sorts the manga however it wants and in any order.

![Screenshot_20220902-215526_Kotatsu](https://user-images.githubusercontent.com/15205162/188256650-6bcac70e-4fb4-4f5a-8aff-9122aa85f305.jpg)

These were imported separately on different days and had nothing to do the time it took to import them. To be clear these are sorted correctly in thier respective folders in the file browser. 

![Screenshot_20220902_221202](https://user-images.githubusercontent.com/15205162/188256829-467cfb6a-dc30-42fa-92b8-bdd97aed90b8.jpg)

I like the different views, but being able to just pick the next volume in the list would be much more enjoyable. Adding this feature to the "list mode" menu or making it its own option in the 3dots menu on the top right seems reasonable.

Please let me know if I'm doing something wrong. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Looks like similar to #217 but do not close this

**Comment by Koitharu** [comment]
Done, available in v4
