### ISSUE TITLE
Chapter download problem 

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/Kotatsu#220]
### Brief summary

 There is a problem with the application when I save the chapters, I cannot open them without the Internet and they do not open again and re-download them again. Please solve the problem

### Steps to reproduce

1- Open the source
2- I choose a manga
3- I download the chapters in order to read them without the Internet
4- It is downloading and the chapters did not appear, but it is re-downloaded again

### Kotatsu version

4.0 -06

### Android version

10

### Device

LG STYLO 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
I guess it's fixed
