### ISSUE TITLE
add option to hide the slider from the bottom bar of the reader

### ISSUE THREAD

**Issue by kalekad** [KotatsuApp/Kotatsu#228]
Kotatsu v4.0-beta1
LineageOS 12.1
Gesture navigation enable
Navigation hint disable

The slider in the bottom bar disrupts the flow of two gestures.

The first is when I want to swipe up from the bottom of the screen in the app (Home gesture).

Second when I want to switch apps by swiping on the bottom of the screen from the right/left corner

Please add an option to hide this slider.

I will also mention that there is an icon on the bottom bar with the same function as the slider, so when hiding the slider one does not lose this feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
We can move slider from bottom bar to the panel above bottom bar? What you think about this?

Example:
|Slider|
----------
|Bottom bar with icons|

**Comment by Koitharu** [comment]
@kalekad 

> Navigation hint disable

I cannot find how to disable it, is it a LineageOS-specific feature?

**Comment by ztimms73** [comment]
Check 4.0-rc1
