### ISSUE TITLE
Local storage loading problem

### ISSUE THREAD

**Issue by luimu64** [KotatsuApp/Kotatsu#230]
### Brief summary

Trying to read manga from local storage with large quantity of chapters (eg. one piece) hangs to black screen until eventually the whole app crashes.

### Steps to reproduce

1. Save one piece to local storage
2. Try reading it

### Kotatsu version

3.4.14

### Android version

12

### Device

Oneplus 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Can you provide a cbz file (using some cloud storage, e.g. Google drive)?

**Comment by ztimms73** [comment]
stale issue, no response
