### ISSUE TITLE
Widget colors are not in sync with the theme

### ISSUE THREAD

**Issue by CuongBa956** [KotatsuApp/Kotatsu#234]
### Brief summary

Kotatsu witget are always darker in color than other system witts. Sometimes with some colors it's almost completely different from the color i choose from wallpaper & style setting and other wigets

### Steps to reproduce

this is the image I compiled when switching some wallpapers with different colors and with 2 other wigets to compare
https://imgur.com/a/MsHcOtP

### Kotatsu version

3.4.16

### Android version

Android 12 

### Device

google pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Try 3.4.16, it should be fixed

**Comment by CuongBa956** [comment]
> Try 3.4.16, it should be fixed

I mistook the exact version I am using is 3.4.16. Compared to the previous version, it fixed the error Witget could not switch to the dark theme but this new error occurred

**Comment by ztimms73** [comment]
I think I need to sort through and compare the colors

**Comment by ztimms73** [comment]
any questions?
