### ISSUE TITLE
Kotatsu's loading Manga Error

### ISSUE THREAD

**Issue by ImpenetrableNoble** [KotatsuApp/Kotatsu#241]
### Brief summary

Hi Kotatsu Team,

I am currently facing an issue where it says "too many requests follow-up 21" I'd like to know why is this happening toward every single manga story I'm reading from different types of manga extensions I'm reading off from? It's been a huge issue for me lately. 

![Screenshot_20221012_053827](https://user-images.githubusercontent.com/104534608/195309585-97b5b641-9d98-401c-9d61-97768240a1b8.png)

![Screenshot_20221012_053819](https://user-images.githubusercontent.com/104534608/195309592-53a7206b-bbaa-4714-ba19-742e2d8f7724.png)

### Steps to reproduce

1. Improve the app.
2. Optimize library and manag extensions.
3. Fix error "too many requests follow-up 21" 
4. Improve chapter updating with mobile notifications. 

### Kotatsu version

3.4.17

### Android version

11.0

### Device

Galaxy A02s 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by anderson-lt** [comment]
I also have an error when opening a Nicovideo Seiga manga, it gives me an error that says image format not supported.
![Screenshot_20221024-202321](https://user-images.githubusercontent.com/65132831/197660161-0e8cb2e3-779a-4435-880f-62e0c2dfd62c.png)

**Comment by ztimms73** [comment]
This gets thrown when there are more than 20 redirects when calling an endpoint. Usually this indicates a redirect cycle between two endpoints. Both Chrome and Firefox will also stop loading the request after this many redirects and fail the request.
© Jack Wharton
