### ISSUE TITLE
status bar color error

### ISSUE THREAD

**Issue by CuongBa956** [KotatsuApp/Kotatsu#244]
![Screenshot_20221020-213944~2](https://user-images.githubusercontent.com/89731755/196981456-09d4cfd8-0ea8-488d-9a44-3a767f7410b5.png)
### Brief summary

My status bar always turns purple when using the app even when I change the theme to other colors but the status bar doesn't change color

### Kotatsu version

4.0

### Android version

Android 12 

### Device

google pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Are you using incognito mode? Because in this mode, status bar color becomes purple

**Comment by CuongBa956** [comment]
> Are you using incognito mode? Because in this mode, status bar color becomes purple. We did this on purpose so that the user knows that he has turned on incognito mode

thanks for the reminder I accidentally turned on incognito mode without noticing the status bar is back to normal.
