### ISSUE TITLE
Clicking options crashes app

### ISSUE THREAD

**Issue by scrazzz** [KotatsuApp/Kotatsu#247]
### Brief summary

Clicking on the 3 dots at the bottom right corner crashes the app 

### Steps to reproduce

1. Open any manga
2. Click the 3 dots at the bottom right corner

### Kotatsu version

4.0.1

### Android version

11

### Device

Oppo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Whoops, we broke autoswitching pages slider. Create backup and rollback to 4.0 if possible

**Comment by Koitharu** [comment]
Should be fixed in v4.0.2

**Comment by conbian12544** [comment]
希望能够点击漫画进去后，阅读的按键放置在左边，或者有一个开关，可以点击漫画直接阅读

**Comment by scrazzz** [comment]
Closing since this bug has been fixed in v4.0.2 (https://github.com/KotatsuApp/Kotatsu/commit/cec19c3db37b3a34729c893b8f8a162855f44c4b)

**Comment by conbian12544** [comment]
更改漫画阅读按钮，单手平板阅读点击不到阅读按钮，如果能听取，感谢



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 24, 2022 20:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KotatsuApp/Kotatsu] Clicking options crashes app (Issue #247)




 
Closing since this bug has been fixed in v4.0.2 (cec19c3)

**Comment by scrazzz** [comment]
@conbian12544 Please open another issue to state your problem.

**Comment by conbian12544** [comment]
Place the reading button in the section below the reading





---Original---
From: ***@***.***&gt;
Date: Tue, Oct 25, 2022 02:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KotatsuApp/Kotatsu] Clicking options crashes app (Issue #247)




 
@conbian12544 Please open another issue to state your problem.
