### ISSUE TITLE
adding extensions

### ISSUE THREAD

**Issue by Yuzumiy** [KotatsuApp/Kotatsu#250]
### Describe your suggested feature

hi, if it's not too much to ask, could you add more extensions? I'm from Brazil, and there are few extensions translated into Portuguese compared to English, and of course not only Portuguese but also other languages. Thanks for your effort!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues
