### ISSUE TITLE
Suggestion / Related feature 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [KotatsuApp/Kotatsu#254]
### Describe your suggested feature

Hi Kotatsu,

Your "related" and "suggestions" feature in your app to suggest any manga stories from different manga extensions is wonderful however I was hoping if you're able to improve them a little more by showing simple stats data for which manga would be more suitable for any user to read and the total result of how much users have read. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by jadsongmatos** [comment]
I found this library that is used for movie recommendation maybe to use for mangas with few modifications I believe what do you think?

[https://github.com/tensorflow/recommenders](https://github.com/tensorflow/recommenders)

**Comment by ztimms73** [comment]
@jadsongmatos we are already have a recommendation mechanism that works based on the genres of the manga you have read (manga in history)

**Comment by ztimms73** [comment]
> I looked inside the app but I didn't find it, where is it?

Options -> Settings -> Content -> Recommendations

**Comment by ztimms73** [comment]
There are no plans for this stuff, sorry
