### ISSUE TITLE
please simplify

### ISSUE THREAD

**Issue by FIONover** [KotatsuApp/Kotatsu#255]
### Describe your suggested feature

Я смотрю, и после обновления главная страница выглядит просто ужасно, повторяющийся элементы и т.д. Как по мне стоит убрать полку с историей или передвинуть её в самый конец, а вкладку updated как то совместить с feed, так как они делают почти одно и тоже, либо её вообще убрать так как её функциональ по большей части есть в feed
![Screenshot_20221026-113852_Kotatsu](https://user-images.githubusercontent.com/92229942/197966560-56151b7d-a26b-41b4-ac2f-b89b8662da69.png)
(На скриншоте выше каталог Reading мой собственный, куда я закидываю то что я читаю прямо сейчас ☺️)

Написал на русском, так как заметил что пожертвования идут через Юмани.
Сппсибо за внимание !)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Разделы Обновления, Сохранённое, История в скором времени можно будет отключать в полке. Полка - важный элемент приложения, убирать его не стоит.

**Comment by FIONover** [comment]
Ну, я не имел ввиду убирать полку, но кажется вы меня поняли. Очень круто что скоро эти функции будут добавлени !)
Спасибо большое !
