### ISSUE TITLE
Source Recommendations

### ISSUE THREAD

**Issue by Durgesh002** [KotatsuApp/Kotatsu#258]
### Describe your suggested feature

Could you add mangasee and mangakatana sources in the app? [Mangasee](https://mangasee123.com/) [Mangakatana](https://mangakatana.com/) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Wrong repo. https://github.com/KotatsuApp/kotatsu-parsers
