### ISSUE TITLE
Show favourite marker in manga list

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/Kotatsu#259]
### Describe your suggested feature

Shows in the extension if the comic has been bookmarked 

### Other details

Shows a sign if the comic has been bookmarked in the extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
> bookmarked
Do you mean favorites?

**Comment by alpqm** [comment]
> > di-bookmark
> 
> Maksudnya favorit?

Yes
