### ISSUE TITLE
Feature Request : Crop Borders

### ISSUE THREAD

**Issue by anidevrev** [KotatsuApp/Kotatsu#261]
Please add a feature to crop the white borders in a manga page to make the main content bigger just like in Tachiyomi or Aniyomi - it's an earnest request

**Comment by ztimms73** [comment]
Is it necessary?

**Comment by anidevrev** [comment]
Actually yes, it's a major relief to the eyes as it makes the smaller texts in the page slightly bigger by getting rid of the borders - it would really be extremely helpful if you add this feature

**Comment by Koitharu** [comment]
Why closed?
