### ISSUE TITLE
Missing some shelves

### ISSUE THREAD

**Issue by techie177** [KotatsuApp/Kotatsu#262]
### Brief summary

I noticed after I updated my app from version 4.0.2 to version 4.0.3 I lost both the Currently Reading and the Read Later shelves. Was the removal of those two sections what was being referring to in the 4.0.3 change log about Shelf sections and order settings?

### Kotatsu version

4.0.3

### Android version

Lineage 81.1

### Device

OnePlus 7T Model HD1905

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Configure your shelf in Shelf -> 3-dot icon -> Settings
