### ISSUE TITLE
Allow storing downloaded titles in a custom location accessible without root access.

### ISSUE THREAD

**Issue by voidscuttle** [KotatsuApp/Kotatsu#264]
### Describe your suggested feature

I'd like to be able to back up local data e.g. downloaded/saved titles. I looked through the application settings and searched the Github issues (custom folder) and as far as I can tell this does not seem possible without root access. 

Kotatsu stores downloaded titles under `Android/data/..` which is not accessible without root access. It would be a decent addition if the _Folder for Downloads_ setting offered an option for a custom location e.g. Internal-storage/SomeCustomUserCreatedFolder. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
- Local manga storing uses the "File" api that is available only for application`s internal directories (Android/data) starting from android 10. I think we can try to enable it on Android versions where it is supported.
- `Android/data` is accessible without root (anyway on my phone with A12 it is), try [Total Commander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander) for it
- You also can simply click "Share" on saved manga to export the local file

**Comment by voidscuttle** [comment]
> * Local manga storing uses the "File" api that is available only for application`s internal directories (Android/data) starting from android 10. I think we can try to enable it on Android versions where it is supported.
> 
>     * `Android/data` is accessible without root (at least on my phone with A12 it is), try [Total Commander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander) for it

My phone running Android 13 does not seem to be able to. Using TotalCommander (and other FMs) show a prompt but are not able to access the files:

```
"Write protected! On Android >=11, the external SD card is write protected. Location: Android/data

You need to choose the directory from a special Android dialog to give Total Commander write rights"
```

Pressing yes takes you to the SD card view where you can create and select a new folder, but none of the existing folders are eligible for selection.

I am however able to access the folder if I mount the phone on a PC, which makes this request - for me at least - redundant.
