### ISSUE TITLE
Cleared history still shows up in search

### ISSUE THREAD

**Issue by Thang1191** [KotatsuApp/Kotatsu#268]
### Brief summary

You can still look up your read history in the search bar even when you have turned on incognito or cleared out your history.

### Steps to reproduce

Example:
-I read an embarrassing comic that I want to hide
-I remove it from history (clear out all history, have incognito turned on, ect.)
-I search up one letter that existed in the comic's name
-The comic shows up

### Kotatsu version

4.0.4

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Clearing history ≠ clearing search history
Swipe to left or right search query to delete it from search history or go to *Options -> Settings -> History and cache* and click *Clear search history*

**Comment by Thang1191** [comment]
> Clearing history ≠ clearing search history Swipe to left or right search query to delete it from search history or go to _Options -> Settings -> History and cache_ and click _Clear search history_

I did that as well and the issue was still there

**Comment by Koitharu** [comment]
These are suggestions based on all known mangas. I agree that this might be a bad idea due to a breach of privacy
