### ISSUE TITLE
Sync feature will delete any existing Favourites category

### ISSUE THREAD

**Issue by asdrubale88** [KotatsuApp/Kotatsu#270]
### Brief summary

Morning everyone,

I'm trying for the first time the Sync feature of Kotatsu.

Unfortuantely, it seems to wipe out any existing category when I sync it online.

I tried creating a new Favourites category from scratch, either empty of adding some manga in it, however as soon as I manually hit  "Sync now" it will be gone.

Tl:dr --> **The "Sync now" feature will preserve the history, but it will remove any existing Favourite category.**

### Steps to reproduce

1. Create a Favourite category "TEST"
2. Enable Sync feature
3. Hit "Sync now"
4. Check back and the Favouite category "TEST" (as well as any other existing category) is now gone

### Kotatsu version

4.0.5

### Android version

Android 13 - One UI 5.0

### Device

Samsung A33 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ItamiWasTaken** [comment]
This issue seems to persist in the most recent release

**Comment by Koitharu** [comment]
Fixed
