### ISSUE TITLE
How to save cookies?

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/Kotatsu#278]
### Brief summary

Can't save cookies

### Steps to reproduce

1. Go to 'browse'
2. Find Sekaikomik
3. Click 'Finish' captcha
![Screenshot_2022-12-25-16-38-30-876_org koitharu kotatsu](https://user-images.githubusercontent.com/45929526/209463491-e9a92d97-ee29-466f-85c5-bd6f050aebd5.jpg)
![Screenshot_2022-12-25-16-38-34-968_org koitharu kotatsu](https://user-images.githubusercontent.com/45929526/209463509-fdab12a3-48c9-42fc-83d0-8308d6cca223.jpg)
4. There's no 'Ok' button only 'Cancel'
![Screenshot_2022-12-25-16-38-46-003_org koitharu kotatsu](https://user-images.githubusercontent.com/45929526/209463520-01fe4343-32bf-4fcc-b243-cfcd8145cd17.jpg)

-note if this just my lack of Knowledge, please tell me how to fix it
Thank you 

### Kotatsu version

4.0.6

### Android version

12

### Device

Xiaomi Poco x3 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
clear cookies and try again, on my device captcha solving works normal. normally, the dialog should close after solving the captcha

**Comment by MIRVOUS** [comment]
It, work now.
I think my APN wae wrong
