### ISSUE TITLE
Let us change the language of app for android 13 below

### ISSUE THREAD

**Issue by kyoyacchi** [KotatsuApp/Kotatsu#282]
### Describe your suggested feature

Hi. I'd like to be able to change language of the Kotatsu for below android 13. I'm using Android 11, i don't want to use it as Turkish since im trying to improve my English as much as i can.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Will be added as soon as [AppCompat 1.6](https://developer.android.com/jetpack/androidx/releases/appcompat) becomes stable

**Comment by ztimms73** [comment]
Available on v4.3

**Comment by kyoyacchi** [comment]
> Available on v4.3

Nice
