### ISSUE TITLE
Can't login in hentailib or mangalib

### ISSUE THREAD

**Issue by Stratch321** [KotatsuApp/Kotatsu#283]
### Brief summary

I am trying to login to mangalib via source settings, but Sign in button is unavaible with inscription "cannot find username". Sign in function in manga really important since a big amount of manga is unavaible without mangalib account
![Screenshot_2022-12-31-15-42-45-60_a5af3585a93e2016f6667aaf7e1e2f32](https://user-images.githubusercontent.com/49611792/210137131-f855c4e7-3df7-4fe3-9e04-fd5057551f58.jpg)

### Kotatsu version

4.0.6

### Android version

12

### Device

Realme GT 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Update to v4.1

**Comment by Stratch321** [comment]
Now I have 404 error, meanwhile if I trying to open manga in browser, it works
![Screenshot_2022-12-31-16-22-56-67_a5af3585a93e2016f6667aaf7e1e2f32](https://user-images.githubusercontent.com/49611792/210138231-d3d2425e-1835-4b0c-9bec-7ee612664979.jpg)

**Comment by Stratch321** [comment]
I think that happens because of parser didn't use account info for accesing pages 
Kotatsu link is: https://hentailib.me/iljinnyeo-tutoring/v1/c7/
And browser link is :
https://hentailib.me/nyantcha-at-thiccwithaq-comics/v1/c106?ui=2124045

**Comment by ztimms73** [comment]
yes, it's now using user id, I'm working right now on it

**Comment by ztimms73** [comment]
Fixed, wait for next release
