### ISSUE TITLE
Favorites Catalog 

### ISSUE THREAD

**Issue by alucast** [KotatsuApp/Kotatsu#290]
### Describe your suggested feature

Being able to categorize the favorites page by Name Order A-Z, Z-A, or newly added to would be nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Do you mean favorites or bookmarks?

**Comment by Koitharu** [comment]
Reopen this if something wrong
