### ISSUE TITLE
Manhua webtoon progress not saved

### ISSUE THREAD

**Issue by StyraxBenzoin** [KotatsuApp/Kotatsu#292]
### Brief summary

I have tried a few manhua webtoons and read progress is not saved. It always shows chapers as unread and doesn't appear in my history. I have to either remember what chapter I'm on and scroll to the page to get back to where I was, or remember to make a bookmark.

Manga read progress works fine.

### Steps to reproduce

Read a manhua webtoon (e.g. https://manhwa18.net/manga-sex-stopwatch.html). Add it to favourites/read later list. Go back to home screen. See that it does not appear in history. Find it in read later list. See that no reading progress is saved.

### Kotatsu version

4.1.1

### Android version

12

### Device

Samsung Galaxy S10 5G SM-G977B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
maybe you're using incognito mode?

**Comment by StyraxBenzoin** [comment]
No, incognito mode is not active, and other flip page manga progress saves fine. 

I get new chapters update notifications on favourited manhua webtoon, but chapter progress is never saved

![Screenshot_20230107_165211_Kotatsu](https://user-images.githubusercontent.com/66492803/211161654-71ee68ac-2171-4193-a6c3-92217a84ce54.jpg)

**Comment by Koitharu** [comment]
Check if the "Exclude NSFW manga from history" option is not active in Settings->History and cache

**Comment by StyraxBenzoin** [comment]
Sorry, I'm a big dumb dumb :'( didn't realise I had that on.

Thank you, that fixed it.
