### ISSUE TITLE
Add https://9hentai.to/ support

### ISSUE THREAD

**Issue by User1l0** [KotatsuApp/Kotatsu#296]
### Describe your suggested feature

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Time to teach users to go to parsers repo

**Comment by ztimms73** [comment]
> What's that?

https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose
