### ISSUE TITLE
How do I get local chapters to show up as 1 manga?

### ISSUE THREAD

**Issue by LadyHaywood** [KotatsuApp/Kotatsu#305]
### Brief summary

I don't know if it's actually a bug or I'm just placing them wrong? But I can't figure out how to make a manga show all of it's chapters as 1 thing instead of having the chapters show up individually. On top of showing a local manga's metadata. Can I actually do that at this time?

### Steps to reproduce

1. Puts cbz files of chapters into a zip folder
2. Imports them into the app
3. Shows up as a corrupted file with only 1 chapter

### Kotatsu version

4.3.3

### Android version

11.0

### Device

Onyx Boox Nova Air

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Now there are two manga layouts:
1. One cbz = one manga. All pages will be shown in one chapter unless this cbz contains a special index file that is created by kotatsu when downloading the manga.
2. Directory with images, each subdirectory = one chapter

In the future we also plan to support a multi-cbz directory where each cbz = one chapter, but this is not currently supported.

**Comment by LadyHaywood** [comment]
Oops, sorry I didn't see this reply weeks ago. Love seeing that it's being planned. That and epub support would be really nice to have.
