### ISSUE TITLE
Importing in local storage

### ISSUE THREAD

**Issue by BaccanoMob** [KotatsuApp/Kotatsu#31]
How do I access any locally downloaded manga as folders?

![image](https://user-images.githubusercontent.com/82655889/118420093-3ee26d00-b6be-11eb-8e20-86bd4cfe7d26.png)

![image](https://user-images.githubusercontent.com/82655889/118420381-00997d80-b6bf-11eb-96d4-4d40840c1022.png)

I tried clicking the three dots an choosing import but all i can view there are the cbz files individually but can not add as a whole folder as a series. Am I doing something wrong?

**Comment by nv95** [comment]
Now only importing a single cbz file is available. 

You want to import multiple CBZs or something else?

**Comment by BaccanoMob** [comment]
yes, multiple CBZs of any series I have locally so that 1 title shown in the pic wont be chapter 0 but the manga title (the folder name) and in it are the list of CBZ files (chapterwise). This would be beneficial because some manga I have got over 100s of chapters and it is quite chaotic to import them one by one.

**Comment by nv95** [comment]
Could you please give an example of such manga?

**Comment by BaccanoMob** [comment]
Ill try to explain the best I can. What I wanted to suggest was about importing structure.

As far as I can tell, people have local manga as
1) Folder of images
2) Folder of zips either as chapters or volumes (i prefer as chapters so its easier to track)
and the app currently only supports as zips.

For example, take "Itoshi no Karin" manga. It has 3 volumes and 20 chapters. Then I have 20 zip files and I have to import 20 times. Each file is treated as a different manga. But for longer manga it is a big hassle. For example, consider "Nisekoi" which has 25 volumes and 240 chapters. Importing 240 chapters one by one takes time and keeping track is difficult.

So implementing an import structure such as simple as reading and importing one level of zip files in a folder (shown below) would make things efficient.

Case 1:
Manga {Folder}
|--- Chapter 1.cbz
|--- Chapter 2.cbz
:
L--- Chapter x.cbz 

I'm not an expert programmer so I'm not sure how your reader works. If the reader can read images from folder as well, implementing the one below along with the above case would be good.

Case 2:
Manga {Folder}
|--- Chapter 1 {Folder}
     |---001.jpg
     :
     |---xxx.png
|--- Chapter 2 {Folder}
:
L--- Chapter x {Folder}

So, **Import function should import only as folders** (also only read the zip files (case 1) or folders (case 2) and ignore the rest) than import a single zip file at a time. 
When a folder is chosen to import, a list of containing files or folder is created. Then each file/folder is imported under one single manga title. (the basic idea)

Currently importing multiple chapters (say chapter 1, 2 and 3.cbz files) from the same folder named "Manga Title", imports as "chapter 1", "chapter 2" and "chapter 3" manga title separately. It should be under "Manga Title". **That is, Folder name should be the manga title and the list of should be the chapters.** So even if i add a chapter at a later date, it should recognize the folder path. This might be really useful if updating a manga.

Also if my suggestion is implemented, replace "Import" as "Import file" and add my suggestion as "Import batch". I think merging these two as one function might be a bad idea. Im just a beginner at Kotlin so I could be wrong.

Hope this was useful feedback, let me know if you dont understand anything above.

**Comment by BaccanoMob** [comment]
Yes, the case 2 works fine. I prefer case 1 because importing/moving will be faster (that is importing folder of zip files is quicker than folders of images recursively) so I'll wait for it.

**Comment by Koitharu** [comment]
> case 1 because importing/moving will be faster

I think case 1 requires a re-packing files, because one cbz file = one manga

**Comment by ztimms73** [comment]
Available since version 5.0
