### ISSUE TITLE
Kotatsu has issues at connecting to AniList

### ISSUE THREAD

**Issue by PaperJack315** [KotatsuApp/Kotatsu#317]
### Brief summary

When I try to connect Kotatsu to my AniList account, I always receive the same error:"**{"error":"invalid_client","message":"Client authentication failed"}**".

### Steps to reproduce

1. Click on the AniList option in the "Services" section of the app;
2. Wait for the Authentication dialogue box to appear and input the correct account details.
3.Even though I did everything requested to login, I'm redirected to this error. No matter how many times I retry, after the first try I'm always redirected directly to the error message [The hypertext link of the error in question.](https://anilist.co/api/v2/oauth/authorize?client_id=null&redirect_uri=kotatsu://anilist-auth&response_type=code).
![Screenshot_20230304-144114_Firefox_1](https://user-images.githubusercontent.com/28924911/222906050-4e601755-2856-4519-88af-e0124e747c71.png)

### Kotatsu version

4.4.1

### Android version

12

### Device

Xiaomi Redmi Note 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Do you use build from F-Droid?

**Comment by PaperJack315** [comment]
> Do you use build from F-Droid?

Yes, I do.

**Comment by Koitharu** [comment]
Should be fixed in v4.4.4, please wait until it becomes available in f-droid. Sorry for that

**Comment by PaperJack315** [comment]
Don't worry, Koitharu, I've reported the problem because I really like Kotatsu and I want to help.
I'll wait the new update then.
