### ISSUE TITLE
voice search, genre block not found in the app?

### ISSUE THREAD

**Issue by Gamefire238** [KotatsuApp/Kotatsu#318]
### Brief summary

voice search, genre block not found in the app?

the app is not the same as the one in the repo image

### Steps to reproduce

?

### Kotatsu version

4.4.4

### Android version

11

### Device

vivo y12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Voice search needs Google Play services to work (or maybe a Google app)

**Comment by Gamefire238** [comment]
I own it? is the application based on WebView?

**Comment by Koitharu** [comment]
> application based on WebView
No

Voice search icon shown only if Google voice input can be launched

**Comment by Gamefire238** [comment]
so how do you do it, can you tell me more?
