### ISSUE TITLE
Just a question or possible improvement

### ISSUE THREAD

**Issue by MangekyoSharingan** [KotatsuApp/Kotatsu#325]
### Describe your suggested feature

Hey man i was wondering one thing?
Is it possible to update mangas from my library/history myself?
To be more precise,to manually start updates search
Similar as it's on tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Do you mean checking for new chapters?
It is possible to run it manually: go to Feed section and select Update in options menu

**Comment by MangekyoSharingan** [comment]
Thank you
