### ISSUE TITLE
New sortings: Most viewed, highest rated

### ISSUE THREAD

**Issue by fellinir** [KotatsuApp/Kotatsu#337]
### Describe your suggested feature
Please add possibility to sort by most viewed and highest rated, for the supported sources.

### Acknowledgements
- [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
I guess it already exists, it might be missing for some specific source?

**Comment by fellinir** [comment]
@Koitharu I don't see it for N-Hentai for instance

![](https://i.imgur.com/lJtTSC6.png)

**Comment by ztimms73** [comment]
parser specific issue
