### ISSUE TITLE
Disable webtoon scrolling animation

### ISSUE THREAD

**Issue by xl666** [KotatsuApp/Kotatsu#341]
### Describe your suggested feature

In weebtoon view each scrolling tap displays a short animation, which is nice, but it doesn't look as good in an ereader (in highest quality, slow refresh mode). It would be great to be able to disable the animation (as it is possible for page turning)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Do you use a device with e-ink display?

**Comment by Koitharu** [comment]
If you disable animation in system settings, application will respect this configuration (except the Settings screen)

**Comment by jayrfs** [comment]
> If you disable animation in system settings, application will respect this configuration (except the Settings screen)

I'm not sure I understand this correctly. 

This is what you mean right? 

![Screenshot_20230426-185739](https://user-images.githubusercontent.com/74417622/234591065-b29917ac-70fb-49ee-b78c-d1bc16d28ed9.png)

I've set it to 0x and it still animates the page transitions. 

https://user-images.githubusercontent.com/74417622/234591903-17bad650-9522-48ac-9fc0-6bf358f6e27b.mp4

**Comment by Koitharu** [comment]
It depends on the Android version, in common case such option is available in the accessibility settings section

**Comment by jayrfs** [comment]
I have tested this on a 5.0 device and a 13.0 device. Setting the animation duration to 0 doesn't seem to disable the sliding the animations
