### ISSUE TITLE
Filter 

### ISSUE THREAD

**Issue by MrConqueror** [KotatsuApp/Kotatsu#347]
### Describe your suggested feature

![IMG_20230420_094734](https://user-images.githubusercontent.com/102837820/233236829-4b115775-b207-47ff-a8ef-5d77dca8f767.jpg)
This filter should place at the top it's blocking tags

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Try to scroll horizontally this bar with tags

**Comment by MrConqueror** [comment]
> Try to scroll horizontally this bar with tags

I know but wouldn't it be nice if it's on top of it

**Comment by Koitharu** [comment]
We will try to rework this in the future

**Comment by Koitharu** [comment]
Available in v5.2
