### ISSUE TITLE
Uninstalling the app should delete all userdata

### ISSUE THREAD

**Issue by MiquelToni** [KotatsuApp/Kotatsu#354]
### Brief summary

If not a bug, how do I delete all data to start over?

### Steps to reproduce

1. Uninstall or  `clear all data`
2. Install the app
3. Favourites, history and settings persisted 

### Kotatsu version

5.0.1

### Android version

Android 12 (MIUI 13.0.6)

### Device

Xiaomi POCO F2 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
I guess you use synchronization, isn't it?
Your sync account will not be deleted if you clear the app data (this is how Android works) and your history and favourites will be restored via sync. So, you need to delete an account too
