### ISSUE TITLE
Syn issue (failed to connect to the server)

### ISSUE THREAD

**Issue by 0ABDL0** [KotatsuApp/Kotatsu#358]
### Brief summary

When trying to enable sync, it says that the app failed to connect to sync.kotatsu.app/(IP/Port)

Although I'd also request a delete account option on the app so an account can be deleted as it's extremely easy to open an account by accident and it would hurt management of accounts on your end just wanted to let you know that the sync function is not working on the latest version but it's likely a server issue.

### Steps to reproduce

1. Open app
2. Services tab
3. Sync
4. Sync doesn't work

### Kotatsu version

5.0.1

### Android version

12.0

### Device

OnePlus 6 / Poco F3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by 0ABDL0** [comment]
I've just tried again and although it didn't work from 9 AM to 1:34 PM IST time / GTM+3 it currently is back up so I'll close the issue as to prevent unnecessary troubleshooting.

**Comment by ztimms73** [comment]
Some services of the server were unavailable from 30th April 11:43 PM to 1st May 1:29 PM (GMT+3 Moscow time)
