### ISSUE TITLE
Kitsu integration

### ISSUE THREAD

**Issue by xronin01** [KotatsuApp/Kotatsu#360]
### Describe your suggested feature

Kitsu is a modern content discovery platform that helps anime and manga fans track, share and discover more of what they love.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MeteorKLINT** [comment]
There is an open pull request called Kitsu scrobbler #362. Its last commit is from June 2023. Are there plans to accept the pull request and allow the Kitsu integration?
