### ISSUE TITLE
Suggestions updating notification

### ISSUE THREAD

**Issue by NoizIsCool** [KotatsuApp/Kotatsu#368]
### Brief summary

The suggestions updating notification is stuck not moving! 

### Kotatsu version

5.0.1

### Android version

12

### Device

Xiaomi Redmi Note 11S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
try to force close app, WorkManager is buggy now after lib update

https://issuetracker.google.com/issues/270245927
https://issuetracker.google.com/issues/280504155

**Comment by Koitharu** [comment]
Made a workaround for this issue, hope it helps

**Comment by malikshi** [comment]
![Screenshot_2023-06-03-05-52-52-691-edit_org koitharu kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/9080737/9911aaf0-1483-4e2e-88e2-ab1948744bd2)
![Screenshot_2023-06-03-05-53-58-284-edit_com miui securitycenter](https://github.com/KotatsuApp/Kotatsu/assets/9080737/bb3d654e-7e3b-4fdc-82f0-c2de6cea023e)

I had Same issues, Can't remove notifications.

**Comment by Koitharu** [comment]
@malikshi I can`t see any ongoing notification on your screenshot.
To swipe out group of notifications you have to expand it before
