### ISSUE TITLE
Please add a proxy Support 

### ISSUE THREAD

**Issue by Stu75e** [KotatsuApp/Kotatsu#376]
### Describe your suggested feature

Please add support proxy like socks5 or http  in app 🙏 
We have to bypass the entire device through a vpn tunnel. With this feature, we can use this feature only in this program.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Available in v5.2

**Comment by Stu75e** [comment]
🌹♥ Thanks
