### ISSUE TITLE
CAPTCHA test failed on BentoManga

### ISSUE THREAD

**Issue by lezohtml** [KotatsuApp/Kotatsu#400]
### Brief summary

Hi,

Can't pass the captcha test with BentoManga but working fine with the others sources

### Steps to reproduce

1. do a research of you manga
2. some sources ask a captcha request
3. Choose BentoManga
4. Test failed

### Kotatsu version

"5.2.3"

### Android version

"13"

### Device

"Pixel 6a"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Probably fixed in v5.3

**Comment by davvarrr** [comment]
i have V5.3 and its same

**Comment by davvarrr** [comment]
Need to close issue its fixed on 5.3.1
