### ISSUE TITLE
CAPTCHA  failed

### ISSUE THREAD

**Issue by Stu75e** [KotatsuApp/Kotatsu#402]
### Brief summary

This happens after solving the captcha

https://github.com/KotatsuApp/Kotatsu/assets/133971463/e7c72dd5-4386-4c5d-bc6e-371969b8fc05

### Kotatsu version

5.3

### Android version

11

### Device

a20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Try updating to 5.3.1 as it works for me.
you can also delete cookies in the source settings.

**Comment by Stu75e** [comment]
I still have this problem on version 5.3.1
