### ISSUE TITLE
manhwaindo.id 

### ISSUE THREAD

**Issue by julptk** [KotatsuApp/Kotatsu#407]
### Brief summary

no chapter found
![Screenshot_20230702-121407](https://github.com/KotatsuApp/Kotatsu/assets/56266781/75a9e1e5-7ae9-4c0a-9f5f-c80b73cc5bd5)

### Kotatsu version

5.3.2

### Android version

6.0

### Device

Asus x009da

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by davvarrr** [comment]
Its fixed on 5.3.3 , try to update.

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
