### ISSUE TITLE
Display an error message if a captcha is blocked during a manual feed update

### ISSUE THREAD

**Issue by davvarrr** [KotatsuApp/Kotatsu#409]
### Describe your suggested feature

Display an error message if a captcha is blocked during a manual feed update, or display a small popup with the name of the site that needs the captcha to be resolved. 
Because it happens that some eats have new chapters but because of cloudflre blocking you don't realize they exist without manually going to the site. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
sounds good 👍

**Comment by Koitharu** [comment]
Implemented in v6.0

**Comment by davvarrr** [comment]
I've just tested it and it's cool.
Just the notification is displayed as soon as you scroll the source list, I don't think it's relevant to display a captcha resolution notification just when scrolling the sources ( I think it's due to the favicon request ) ( I'll report it if it's not a desired behavior )
thanks for this feature

**Comment by topotech** [comment]
Maybe I should open a new issue for this, but is it normal that the notifications in 6.0 is now flooded with Captcha requests from sources that aren't even enabled (NSFW sources, and sources from languages I haven't selected)

**Comment by ayesc9000** [comment]
Ever since this update, I am flooded with Captcha notifications as soon as I view the sources page. Do you think it would be possible to provide an option to turn off Captcha warnings when viewing the sources page?
