### ISSUE TITLE
Disable all NSWF Manga Sources Feature

### ISSUE THREAD

**Issue by Git08hb** [KotatsuApp/Kotatsu#411]
I want a setting where all NSFW Manga Sources are disabled when you toggle it on

**Comment by I-JMC** [comment]
Me too

**Comment by Koitharu** [comment]
Do you mean hiding nsfw sources from list or nsfw manga (some sources may provide both normal and nsfw manga)

**Comment by Git08hb** [comment]
> Do you mean hiding nsfw sources from list or nsfw manga (some sources may provide both normal and nsfw manga)

Both would be good
