### ISSUE TITLE
Checking for new chapters does not issue notification for completely read mangas.

### ISSUE THREAD

**Issue by RandomParacodes** [KotatsuApp/Kotatsu#415]
### Brief summary

I periodically check in with my favorites that are still in progression and found out about this issue. 

### Steps to reproduce

1. Complete a manga
2. Wait until a new chapter is released on its source
3. Go into the manga profile and see the new chapter available for reading. (additional: the progress icon still leaves as completed even with the new chapter)
4. Check notifications, updates shelf, and/or the feed section, no mentions of new chapters for completely read mangas.

### Kotatsu version

5.3.3

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by RandomParacodes** [comment]
I closed my own issue. Because this issue was present in a previous version, but got fixed thanks to the new update.

**Comment by Koitharu** [comment]
This is a strange behavior
