### ISSUE TITLE
Consider uploading to Accrescent

### ISSUE THREAD

**Issue by ZBE69** [KotatsuApp/Kotatsu#419]
### Describe your suggested feature

[Accrescent](https://accrescent.app) is a modern alternative to F-Droid that allows unprivileged, unattended app updates. Unless there's an objection with the permissions required by Kotatsu, porting it should be very simple.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
GitHub Releases is enough

**Comment by rmsa5** [comment]
very unfortunate...

**Comment by cirnolovetech** [comment]
> GitHub Releases is enough 

Not for security...
