### ISSUE TITLE
New source chosen not pressing in the list of active ones

### ISSUE THREAD

**Issue by davvarrr** [KotatsuApp/Kotatsu#426]
### Brief summary

I just saw this by adding sources.
I don't know if it's only linked to the dev version, but as soon as a new source is available and you can choose them, if you choose one or multiple and confirm, it doesn't appear in the selection list
but it is in the total source list but not selected

### Steps to reproduce

if a new source is available, select it
look at the list of selected sources and see which one is not present.

### Kotatsu version

5.3.8

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by davvarrr** [comment]
Note that if the source selected is not in the language chosen at the start of the app settings, the bug occurs, but if the source is in the language selected, it is added.

**Comment by Koitharu** [comment]
Probably fixed in v6.0
