### ISSUE TITLE
Cannot deselect new sources

### ISSUE THREAD

**Issue by XeroOl** [KotatsuApp/Kotatsu#445]
### Brief summary

When the app updates, it shows a list of new sources.

Each source gets a button to turn it on/off, but the buttons forget their state when scrolled off screen.

### Steps to reproduce

1. Update the app and get a lot of new sources
2. Open the app to get a popup that lists many sources
3. Scroll through and set each one disabled
4. Scroll back up in the list and see that the sources are re-enabled

### Kotatsu version

5.3.10

### Android version

13

### Device

Google Pixel 5 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Known issue, fix will be available in v6

**Comment by Koitharu** [comment]
Fixed in v6.0
