### ISSUE TITLE
Please give the old dynamics theme its own option

### ISSUE THREAD

**Issue by LadyHaywood** [KotatsuApp/Kotatsu#460]
### Describe your suggested feature

I don't know if this tag is fitting but I wasn't sure what to file this under since I couldn't find a "feedback" tag. The new dynamic theme is lighter than before and I personally wish to still have that darker look. Would like to see the old dynamics look as its own theme option.

![PhotoGrid_Site_1692240982263](https://github.com/KotatsuApp/Kotatsu/assets/10987703/b7e83b84-51c4-4791-a979-9e417a43aa1c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
![Screenshot_20230817-084325](https://github.com/KotatsuApp/Kotatsu/assets/61558546/6c53ea0a-097d-459d-8d34-cdb05a38d5a8)
