### ISSUE TITLE
Please add MangaUpdates, Kitsu 

### ISSUE THREAD

**Issue by huxxyfromjupiter** [KotatsuApp/Kotatsu#473]
### Describe your suggested feature

Please add [MangaUpdates](https://www.mangaupdates.com/) & [Kitsu](kitsu.io)  in the tracking list as it consists more manga to track than Anilist & MAL.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by istudyatuni** [comment]
#360 #389

**Comment by ztimms73** [comment]
Duplicate
