### ISSUE TITLE
Add an option to revert back to the old ui

### ISSUE THREAD

**Issue by theerthrajk** [KotatsuApp/Kotatsu#475]
### Describe your suggested feature

Hey I would like to request an option to revert back to old ui because I liked that you could see the new chapters which came in the main page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by theerthrajk** [comment]
It used to be simple like this![224589279-202c18f0-d209-4166-a77e-b8a23ed3c9c6.jpg](https://github.com/KotatsuApp/Kotatsu/assets/63943672/1ae791dc-7905-40d6-9b51-a59a057c09ce)

**Comment by theerthrajk** [comment]
Pls do something 🙏 the new ui is complicated and not user friendly

**Comment by ztimms73** [comment]
You are free to make your own fork or app

> revert back to old ui because I liked

Sure, and many people like you hated it when it first came out, just like any other major UI change.

**Comment by Koitharu** [comment]
The old Shelf UI was a bit complicated and challenging to maintain so we decided to turn it down

**Comment by theerthrajk** [comment]
Ok fine anyway I will still use the app I am just addicted to reading manga and manhwa kotatsu is like my fav app so I was like sad when it's ui changed that I liked so much![Screenshot_20230905_150202.jpg](https://github.com/KotatsuApp/Kotatsu/assets/63943672/a06a8b34-513a-4eb0-9ebf-ab1c094034f8)

As you can see it's one of the most used app that I use

**Comment by Koitharu** [comment]
We are planning to make bottom navigation customizable
