### ISSUE TITLE
Lagging!!!

### ISSUE THREAD

**Issue by Crownprince17** [KotatsuApp/Kotatsu#476]
### Brief summary

Pls fix this app i can't download and my download didn't appear on download section!!!!!!!

### Kotatsu version

v6.0.2

### Android version

11

### Device

OnePlus7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
Provide more info or I'll close this issue

**Comment by ztimms73** [comment]
Additional info was not provided
