### ISSUE TITLE
can't log in with mal

### ISSUE THREAD

**Issue by ghazzor** [KotatsuApp/Kotatsu#477]
### Brief summary

i get error 400 when i try to login with mal in browser and in app i net a null account

### Steps to reproduce

1. open sync settings 
2. click mal
3. log into mal and allow app to access mal acc
4. you get error 400 in browser
5. null account in app

### Kotatsu version

6.0.2

### Android version

12.0 one ui 4.1

### Device

galaxy m21 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by kyoyacchi** [comment]
Just click once on "Allow" button

**Comment by ghazzor** [comment]
> Just click once on "Allow" button

already did that

**Comment by Koitharu** [comment]
Does this error still appearing?

**Comment by ghazzor** [comment]
> Does this error still appearing?

yea

**Comment by Koitharu** [comment]
Unfortunately I cannot reproduce it yet

**Comment by ghazzor** [comment]
is this message ok when logging in with mal
![image](https://github.com/KotatsuApp/Kotatsu/assets/127341071/5ad10884-ca11-42c9-a94f-3caec59badee)

**Comment by ghazzor** [comment]
just switched to anilist , it just works

**Comment by ghazzor** [comment]
Well this works now , so closing
