### ISSUE TITLE
Chain Validation error

### ISSUE THREAD

**Issue by Samarth170102** [KotatsuApp/Kotatsu#479]
### Brief summary

Cannot synchronise the data with existing or new password, it is saying, Chain validation error.

### Kotatsu version

6.0.2

### Android version

Android 12

### Device

OnePlus Nord 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Samarth170102** [comment]
![Screenshot_2023-09-05-01-16-48-08_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/Kotatsu/assets/68531955/4b9213f0-57e5-4dda-9b68-ad0a6f3e7b15)
This is how it looks.

**Comment by ztimms73** [comment]
I'll recreate the certificate for the domain kotatsu.app, please wait

**Comment by ztimms73** [comment]
Done
