### ISSUE TITLE
Feed bug

### ISSUE THREAD

**Issue by Samarth170102** [KotatsuApp/Kotatsu#481]
### Brief summary

![Screenshot_2023-09-05-11-03-27-25_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/Kotatsu/assets/68531955/b70bc45e-0765-4a73-b333-65970831316a)
When manga get an update, that update do not show in feed like before, it was okay in 5.3.0.

### Kotatsu version

6.0.2

### Android version

Android 12

### Device

OnePlus nord 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Did you received at least one notification about new chapters?

**Comment by Samarth170102** [comment]
No, I didn't receive it, I uninstalled the 5.3.0 and download the 6.0
version, and then synchronise all the data,in 6.0 no updates were received.
Maybe because of that program bar is also not showing current % even after
the update come for manga.

**Comment by Koitharu** [comment]
>  bar is also not showing current %
Yes

Double-check the settings and try to update feed manually (via 3-dots menu)

**Comment by Samarth170102** [comment]
For the temporary time I had switched to 5.3 version of this, and updates
were received well,now I have updated to 6.0.3, under 2-3 days I'll let you
know if I still recieved update or not in 6.0.3.

**Comment by Samarth170102** [comment]
It is working well now, updates are coming and  progress bar is also
working well, thank you.

**Comment by Samarth170102** [comment]
Problem solved
