### ISSUE TITLE
Query about the in-app bug report system in Kotatsu

### ISSUE THREAD

**Issue by wfey12** [KotatsuApp/Kotatsu#485]
### Brief summary

I encountered an error today, but I accidentally swipe back, and I can’t reproduce it. Now it left me wondering about the built-in bug reporting system. Does this app automatically submit the error message to the developer in-app, or do I need to manually fill in a report form in GitHub, such as these? 

### Steps to reproduce

n/a

### Kotatsu version

6.03

### Android version

12

### Device

Samsung Galaxy S22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Crashes are being sent to our server using [ACRA](https://github.com/ACRA/acra) but it required explicit approving from user each time, so crash report has been sent only if you press "Send" in the corresponding dialog

**Comment by ztimms73** [comment]
Yes, error reports are stored in the device memory and wait to be sent until the network is available
