### ISSUE TITLE
Main Screen Section duplicate search results bug

### ISSUE THREAD

**Issue by sinjoe** [KotatsuApp/Kotatsu#495]
### Brief summary

Searching anything in ~~Explore search bar~~any Main Screen Section's Search bar, opens 1 extra search result. Have to go back twice to see search bar again.

Searching directly on any source only need to back once to see source main page.
Find similar option only need to back once aswell.

~~Only Explore search bar loads 2 results query? I dont know if this is the right word~~

Correction, this happens in any Main Screen Section Search bar. Be it in Update/History/Explore/Favourites. Duplicate results bug happen.

Nevermind i can edit the title, my bad

### Steps to reproduce

- search anything in any Main Screen Section's Search Bar
- results shows
- back once, shows the exact same result
- back one more time, search bar finally shows up

### Kotatsu version

6.1.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
I do not totally understand what you mean, can you please provide some screenshots or a screencast?
