### ISSUE TITLE
Add Source ksk.moe

### ISSUE THREAD

**Issue by theerthrajk** [KotatsuApp/Kotatsu#496]
### Describe your suggested feature

Adding Hentai manga Source - https://ksk.moe/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Open issue in [kotatsu-parsers repo](https://github.com/KotatsuApp/kotatsu-parsers)
