### ISSUE TITLE
Restore Function by File.

### ISSUE THREAD

**Issue by Not-A-Syntax** [KotatsuApp/Kotatsu#503]
### Describe your suggested feature

Im Migranting from Tachiyomi to Kotatsu, The app is more stable e working better with most of the Brazillian's Websites.

I have a friend who will migrate soon too. and i would like to share my library with him. without him needing to enter in my account. in Tachiyomi it has a button that you can restore a point from a file who you can create a backup. so you could add a system like that to share currently library. if possible. a system that's compatible with Tachiyomi's restore file too. for better migrate from futures users.

Srry for my bad english

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
You can create and restore backup using Settings -> Data and privacy -> Create data backup / Restore from backup

**Comment by Not-A-Syntax** [comment]
> You can create and restore backup using Settings -> Data and privacy -> Create data backup / Restore from backup
> 
> But it is not compatible with Tachiyomi and it's impossible to do

Thanks. at least i can use that function to save my friend. i didn't saw it. sorry for the inconvinience.
