### ISSUE TITLE
High Quality Image Bug

### ISSUE THREAD

**Issue by Samarth170102** [KotatsuApp/Kotatsu#505]
### Brief summary

So when the image quality is high it has show some type of lines in gray color mostly, and if I zoom it those line goes away. See the image below for Better idea.

### Steps to reproduce

![Screenshot_2023-09-21-13-40-48-51_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/Kotatsu/assets/68531955/4caa329c-db20-4784-b99e-cce3e14645bc)
![Screenshot_2023-09-21-13-40-57-71_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/Kotatsu/assets/68531955/5d8bce1a-acb8-4b08-a974-c76e2906999f)

### Kotatsu version

6.1.3

### Android version

Android 12

### Device

OnePlus Nord 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
I think we need to implement 32-bit color setting

**Comment by ztimms73** [comment]
This effect is quite normal, it always happens when the strokes are very thin and close to each other

**Comment by Koitharu** [comment]
Ok I need a link to such image

**Comment by Samarth170102** [comment]
https://mangadex.org/chapter/c8c98a73-af21-4bce-86d9-f06ebd7a4faf/7

**Comment by ztimms73** [comment]
enable 32-bit color setting ig
