### ISSUE TITLE
Mangalek source stop working

### ISSUE THREAD

**Issue by codered21** [KotatsuApp/Kotatsu#507]
### Brief summary

Mangalek the most important Arabic resource, suddenly stopped working, even though the Internet page was working properly

### Kotatsu version

6.1.3

### Android version

12

### Device

Galxsy note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
https://github.com/KotatsuApp/kotatsu-parsers

**Comment by codered21** [comment]
why closed ?

**Comment by ztimms73** [comment]
please read what you acknowledge
