### ISSUE TITLE
Kotatsu colors

### ISSUE THREAD

**Issue by TheRemakerMan** [KotatsuApp/Kotatsu#515]
### Brief summary

Where and how did you generate the colors for the themes? in values/colors_kotatsu.xml in this commit b00bc22eadaafd7d931b33c6d9e9a550217f728a

### Kotatsu version

6.1.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by TheRemakerMan** [comment]
material theme builder doesn't generate some colors like surface container high

**Comment by Koitharu** [comment]
@Xtimms

**Comment by Koitharu** [comment]
@ztimms73

**Comment by ztimms73** [comment]
I'm using this plugin for Figma

https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder

Then I'm generating a palette with this plugin and I get a list of colors. When I'm at the PC, I'll show you in the form of screenshots.

**Comment by TheRemakerMan** [comment]
Thanks, I figured out how to get some colors.
