### ISSUE TITLE
Mangasee sort?

### ISSUE THREAD

**Issue by moe123s** [KotatsuApp/Kotatsu#523]
### Brief summary

Mangasee has only sorting by name while in tachiyomi it has sorting by popularity, name etc

### Steps to reproduce

Explore mangasee filter. You only can do by name not popularity like tachiyomij2k

### Kotatsu version

6.1.6

### Android version

13

### Device

Galaxy fold 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
Create issue in [parsers repo](https://github.com/KotatsuApp/kotatsu-parsers). We do not accept source issues in the app repository
