### ISSUE TITLE
Ability to pin sources 

### ISSUE THREAD

**Issue by kyoyacchi** [KotatsuApp/Kotatsu#531]
### Describe your suggested feature

I know we can move the sources but having a "pinned" sources column would be better for using some sources.
I'm surprised no one has requested this feature yet 🤔

Example:

![Screenshot_20231017-162115](https://github.com/KotatsuApp/Kotatsu/assets/63583961/01818e5e-3ab7-435b-a503-01e322f8430d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by zPilax** [comment]
I think the reason for this would be:
It is easier for the user to pin the source rather than dragging the source up from the bottom/any place, from my experience it is tedious to drag the source to the top

**Comment by VictorFeroli** [comment]
> why would this be better? we need a reason. as you wrote, sources can be moved up. also, they can be placed as shortcuts on the desktop of the launcher

I believe it would be good to create a setting to limit the manga search to only pinned sources, for example

**Comment by Sky-Poem** [comment]
Aside from the ability to only search pinned sources it can help to find most used sources faster

As an example let's say I use sources x,y,z the most and are scattered around on the list. It will make it super easy to access them when needed

**Comment by aminoginji** [comment]
Sources cannot be moved or reorganized. Shortcuts can be made but it would be nice to have pined sources at the top for searching.  It would help with source requests

**Comment by ztimms73** [comment]
Sources can be moved or reorganized in Settings -> Manga sources -> Manage sources

**Comment by aminoginji** [comment]
> Sources can be moved or reorganized in Settings -> Manga sources -> Manage sources

Does not work for me 
![Screenshot_20240212-013621](https://github.com/KotatsuApp/Kotatsu/assets/1223153/d44d06c8-b05f-44ba-abf7-8c2b3e925ccb)
![Screenshot_20240212-013612](https://github.com/KotatsuApp/Kotatsu/assets/1223153/2fd3e479-4e7b-43e4-985d-956ebaf67be2)
I cannot drag or move in list or icon on any of my devices

**Comment by aminoginji** [comment]
> Sources can be moved or reorganized in Settings -> Manga sources -> Manage sources

Found it

**Comment by aminoginji** [comment]
Could definitely use to top when searching for a source
![Screenshot_20240212-014030](https://github.com/KotatsuApp/Kotatsu/assets/1223153/42fddb07-640a-4c63-be56-70d07803bd6e)
