### ISSUE TITLE
Saved manga bug

### ISSUE THREAD

**Issue by AdityaMH** [KotatsuApp/Kotatsu#534]
### Brief summary

The app keep force me to connect to internet when pick saved manga or want to read saved manga. if keep turn off data, page only show title or error.

### Steps to reproduce

turn off data, then pick downloaded manga.

### Kotatsu version

6.2.2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by zPilax** [comment]
Hello for this issue, i have a temporary fix for you to read downloaded chapters.

Step 1 - Turn off internet
Step 2 - Close Kotatsu App
Step 3 - Re-open kotatsu app while not connected to the internet
Step 4 - Read downloaded chapters

**Comment by AdityaMH** [comment]
that method still imposible to me.
very useless downloading manga from this app.
Because don't let you to read offline.
