### ISSUE TITLE
ADD REAPER SCANS

### ISSUE THREAD

**Issue by Cassian66** [KotatsuApp/Kotatsu#535]
### Describe your suggested feature

REAPER SCANS IS A POPULAR SITE FOR READING MANHWAS.LOTS OF GOOD WEBTOONS ARE AVAILABLE IN IT WITH QUALITY TRANSLATIONS.THE EXISTING REAPER SCANS EXTENSION IS NOT IN ENGLISH LANGUAGE AND HAVE ERRORS IN OPENING .LINK FOR REAPER SCANS https://reaperscans.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
please turn off caps lock.
source requests should opening [here](https://github.com/KotatsuApp/kotatsu-parsers)
closing.
