### ISSUE TITLE
DL offline 

### ISSUE THREAD

**Issue by davvarrr** [KotatsuApp/Kotatsu#547]
### Brief summary

I've downloaded some chapters and it's impossible to read them offline. I always need an internet connection. 

### Kotatsu version

6.2.6

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by zPilax** [comment]
Hello for this issue, i have a temporary fix for you to read downloaded chapters.

Step 1 - Turn off internet
Step 2 - Close Kotatsu App
Step 3 - Re-open kotatsu app while not connected to the internet
Step 4 - Read downloaded chapters

**Comment by davvarrr** [comment]
The fix works for listing chapters but not for reading them without internet. I get network errors, and if you don't have internet for more than a few days you can't read anything, not even list chapters. 
The download section should not update any data if there is no internet but just list the downloaded chapters and display the pages of the downloaded chapters.

**Comment by AdityaMH** [comment]
#534

**Comment by Koitharu** [comment]
Can you please share some screencasts?

**Comment by davvarrr** [comment]
![Screenshot_20231116-182742](https://github.com/KotatsuApp/Kotatsu/assets/70220050/c22c65cd-83f4-49bd-b1b1-4026928d9bec)
Screenshoot taken in the download section without preloading the manga avent (otherwise preload the manga gives are in cash and displays the chapters but the concern also comes on the manga pages)

**Comment by Koitharu** [comment]
Yea, looks like download item opens an online variant
