### ISSUE TITLE
Add a local source

### ISSUE THREAD

**Issue by zPilax** [KotatsuApp/Kotatsu#551]
### Describe your suggested feature

To add a local source for my mangas residing in my network/ or to add Komga/Kavita on the sources list

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
> local source

There it is, isn't it? 

![Screenshot_20231109-090412](https://github.com/KotatsuApp/Kotatsu/assets/61558546/e3781125-3317-4885-afaa-21458ecc6862)

**Comment by AdityaMH** [comment]
i can't download from custom folder either.

**Comment by zPilax** [comment]
> > local source
> 
> There it is, isn't it?
> 
> ![Screenshot_20231109-090412](https://user-images.githubusercontent.com/61558546/281632847-e3781125-3317-4885-afaa-21458ecc6862.png)

what i mean here is, i have a manga collection on my network running on komga, i would like to have an extension for komga, just like tachiyomi has

**Comment by ztimms73** [comment]
Then https://github.com/KotatsuApp/kotatsu-parsers/issues/101
