### ISSUE TITLE
pages cache for saved manga is redundant and unnecessary 

### ISSUE THREAD

**Issue by sadboy889** [KotatsuApp/Kotatsu#552]
### Describe your suggested feature

hello respected developers!

for local/saved files there is no need for cached pages, i wish kotatsu can just read the files instead of unnecessarily creating copies somewhere, it will also help the app consume less power

i do know you can just clear the cache but this is just redundant, why cache even needed for local files at all? it's bloating my limited storage until i clear it manually

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
If manga stored in zip/cbz archive it is impossible to display its pages directly

**Comment by sadboy889** [comment]
> If manga stored in zip/cbz archive it is impossible to display its pages directly

its shouldn't be... then how did tachiyomi/hentoid did it? they can read cbz archive just fine directly, and i check my storage frequently and i dont see any extra cache suddenly bloating my storage from using their app
