### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by BadWolf-63** [KotatsuApp/Kotatsu#553]
### Brief summary

Ok, this version crashes constantly, and even when closed i get a ton of messages "an error occurred".
Most of the sites are unreachable, giving various errors.
I cannot go back to the previous one because the "backup" option creates files with 0 Byte lenght.

### Kotatsu version

6.2.7

### Android version

5.1

### Device

LG VS880

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
hello, please, can you share a crash log?

**Comment by BadWolf-63** [comment]
where do i find it?
At the moment i have uninstalled it and put back the old version, but i can reinstall it again

**Comment by BadWolf-63** [comment]
where do i find it?

**Comment by BadWolf-63** [comment]
accessing the source sites most of the time gives an error in 

org.jsoup.parse.tag

**Comment by BadWolf-63** [comment]
Great Job!!!
I still have to try the backups, but the rest is working flawlessly.
Thank you so much.
    On Thursday, November 23, 2023, 03:11:18 AM CST, Koitharu ***@***.***> wrote:  
 
 


Please check whether it is fixed in v6.3
