### ISSUE TITLE
Add new Sources

### ISSUE THREAD

**Issue by mariodac** [KotatsuApp/Kotatsu#555]
### Describe your suggested feature

I would like you to add these sources of comics:
- Name:Arte HQs URL: http://www.artehqs.com.br
- Name: Tropa BR 2.0 URL: https://tropabrscans.blogspot.com
- Name: HQ Livre URL: https://hqlivre.com
- Name: HQ Now URL: https://www.hq-now.com
- Name: Galáxia dos Quadrinhos URL: https://www.galaxiadosquadrinhos.com.br
- Name: Timeline Comics URL: https://timelinecomics.blogspot.com
- Name: Projeto HQ Online URL: https://projetohqonline.blogspot.com
- Name: Banda Desenha URL: https://bandadesenhada-pt.blogspot.com
- Name: Baixar Quadrinhos URL: https://baixarquadrinhos.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
https://github.com/KotatsuApp/kotatsu-parsers

**Comment by CintiaM1907** [comment]
Alguma sites estão mudando e usando o mesmo formato ,que não dá mais para ver tipo sinensistoon.com
Cericetoon.com
Como resolver?

**Comment by Koitharu** [comment]
Use English please

**Comment by mariodac** [comment]
> Alguma sites estão mudando e usando o mesmo formato ,que não dá mais para ver tipo sinensistoon.com Cericetoon.com Como resolver?

- Vai em Explorar
- Seleciona a fonte que quer
- Dentro da fonte vai nos 3 pontinhos 
- Depois vai em configurações 
- Só configurar o domínio e voltar que vai tá salvo
