### ISSUE TITLE
captcha removing

### ISSUE THREAD

**Issue by semokkuklek** [KotatsuApp/Kotatsu#559]
### Describe your suggested feature

hello, there are too many "source needs captcha notifications, even from sources I don't read from.
I searched through settings but didn't find how could turn this function off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
You can turn off these notifications in system notifications settings
