### ISSUE TITLE
manga source does not appear

### ISSUE THREAD

**Issue by nvanadsn** [KotatsuApp/Kotatsu#561]
### Brief summary

![Screenshot_20231119-002359_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/146634373/c96c772d-f1fb-4ede-8e6e-6174e94eb7dd)

Manga sources in Indonesian do not appear, in previous versions there were no problems

### Kotatsu version

6.3

### Android version

13

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
You might already have added all available sources.

**Comment by davvarrr** [comment]
No I have the same concern and I don't have an active id source.

**Comment by nvanadsn** [comment]
> You might already have added all available sources.



> You might already have added all available sources.

no, I just added some sources

**Comment by nvanadsn** [comment]
> You might already have added all available sources.

**Comment by nvanadsn** [comment]
I hope this can be fixed as soon as possible

**Comment by ztimms73** [comment]
Is "New manga sources available" tip on the Explore screen visible? Try to click Manage or Discard, then try again

**Comment by nvanadsn** [comment]
> Is "New manga sources available" tip on the Explore screen visible? Try to click Manage or Discard, then try again

I've tried this, but it's still the same. In the latest update 6.3.1 it still doesn't show existing sources

**Comment by nvanadsn** [comment]
> You might already have added all available sources.

No, I only added a few sources, there should still be several sources that I haven't added.

**Comment by Spot-nabil** [comment]
I have the same issue. Any fix yet?

**Comment by nvanadsn** [comment]
> I have the same issue. Any fix yet?

There is no change in the most recent version 6.3.1.

**Comment by nvanadsn** [comment]
In the latest update, v6.4 has been improved, and now it is optimized. Thank you developer🤩
