### ISSUE TITLE
Webtoon/Translate Webtoon

### ISSUE THREAD

**Issue by Fuzzythegoatq** [KotatsuApp/Kotatsu#567]
### Describe your suggested feature

Best Source For Comics And Manhwa Everywhere!

https://m.webtoons.com/en/
https://translate.webtoons.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
open in kotatsu-parsers repo

**Comment by ztimms73** [comment]
wait, no, line webtoons exist
