### ISSUE TITLE
There appears to be an issue with the Otsugami ID extension.

### ISSUE THREAD

**Issue by nvanadsn** [KotatsuApp/Kotatsu#568]
### Brief summary

![Screenshot_20231123-112955_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/146634373/63e1bf34-ea5f-4347-bc19-655927dfa5b1)

The arrangement of the chapters does not correspond to the numbers listed, for example chapter 20 in section one.

### Kotatsu version

6.3

### Android version

13

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
If this is an issue with a parser, I should be opening an issue in the parsers repository?

**Comment by nvanadsn** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository?

Of course
