### ISSUE TITLE
Can't read downloaded manga. App always load from internet. 

### ISSUE THREAD

**Issue by LemonCat** [KotatsuApp/Kotatsu#577]
### Brief summary

I can download chapters, but they are never used. I have 5Gb of space taken by downloaded chapters, but if I'm offline I can't read them, the app still try to display from internet. 

No response
Kotatsu version

5.3.3
Android version

Android 6
Device

Asus X009DA and Xiomi note 4
Acknowledgements

    I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
    If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

### Steps to reproduce

1. Download chapters (I'm currently having the problem with the source ColoredMange)
2. Turn ON plane mode
3. Try to read downloaded manga

### Kotatsu version

6.3.0

### Android version

11

### Device

OnePlus Nord N10 5G 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by davvarrr** [comment]
This has been fixed, update your application and test if it works or not.

**Comment by LemonCat** [comment]
It is indeed fixed. Thank you for your work!
