### ISSUE TITLE
Zoom feature is limited in recent version

### ISSUE THREAD

**Issue by Jigyassu** [KotatsuApp/Kotatsu#579]
### Describe your suggested feature

Zoom feature is best till 6.3.1 why it got limited in latest version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
What do you mean by "limited"? And also did you try v6.4.2? It has some fixes related to zoom in webtoon mode
