### ISSUE TITLE
It is impossible to synchronize Kotatsu

### ISSUE THREAD

**Issue by Tapo4ina** [KotatsuApp/Kotatsu#586]
### Brief summary

When trying to synchronize via Kotatsu, he writes a "Network error" by email. At the same time, there is an Internet connection...

### Steps to reproduce

Bug:
1. Log in to the Service
2. Click in Sync, enter your email and password
3. To see the error 

### Kotatsu version

6.4.2

### Android version

Android 12

### Device

Device: F+ Model: SP65 6GB/64GB 4000mAh GMS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Tapo4ina** [comment]
![Screenshot_20231205-230223](https://github.com/KotatsuApp/Kotatsu/assets/95134475/fc0c47b6-330b-44dc-b1ce-b81cd8cbc6cc)

**Comment by ztimms73** [comment]
Sync server is down

**Comment by Tapo4ina** [comment]
> Синхронизация сервера не работает
When will they be restored? In my opinion, they fell for 3 more days, and they still don't work...

**Comment by yoshikuniii** [comment]
It's seems to be working again now, but my reading history empty now

**Comment by Frostedfox** [comment]
Sync server is down

**Comment by Frostedfox** [comment]
Sync Server is down
