### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by Pantyhose-X** [KotatsuApp/Kotatsu#591]
### Describe your suggested feature

[Build Tor into your app, and Integrate with external Orbot or TorServices app](https://tordev.guardianproject.info/mobile-concepts/all-the-ways-to-torify)
> If you do not want to add the additional code complexity and size directly into your app, you can instead only offer active Tor features if the user has [Orbot](https://github.com/tor-on-android/netcipher-with-orbot-legacy) or [TorServices](https://github.com/tor-on-android/torservices) installed on their device. Apps like [F-Droid](https://github.com/mobile-apps-with-tor), [Save by OpenArchive](https://github.com/mobile-apps-with-tor), and [ReThinkDNS](https://github.com/mobile-apps-with-tor) do this today, to enable proxying through Tor without having to build in all of Tor.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Is it necessary?

**Comment by Pantyhose-X** [comment]
> Is it necessary?

In regions such as China, Iran, North Korea, Ukraine, etc., it is difficult to connect to a Kotatsu 500+ sources
TOR can bypass the website or ISP GFW limit blockade

Alternative solutions
Maybe built-in Hosts and DoH to deal with DNS pollution.

**Comment by Koitharu** [comment]
I suppose Orbot supports any application via VPN, isn`t it?

**Comment by 77-77SP** [comment]
> I suppose Orbot supports any application via VPN, isn`t it?

I agree with you, Orbot supports any application via VPN. Also, DOH can be set in any modern smartphone natively in settings.
