### ISSUE TITLE
Kotatsu previous features are good

### ISSUE THREAD

**Issue by Colorstips** [KotatsuApp/Kotatsu#595]
### Brief summary

Kotatsu previous features are good,but now it's  
Very unsatisfying comick previous features 
Are good all chapters are available beetoon 
All chapters in website available not in kotatsu 
This is the biggest issue in kotatsu

### Kotatsu version

6.2

### Android version

6.0

### Device

Vivo1908

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
what are you talking about?

**Comment by AdityaMH** [comment]
Some comic cannot be readed due "chain validation failed issue". Not kotatsu fault, actually.
