### ISSUE TITLE
Auto download Updated chapters 

### ISSUE THREAD

**Issue by Tareq4322** [KotatsuApp/Kotatsu#602]
### Describe your suggested feature

It will be really helpful if the updated chapters are downloaded automatically, as they update in the background, and we don't have to wait for pages to load and can read updated manga without interruptions.
![Screenshot_20231222-103649_TachiyomiJ2K](https://github.com/KotatsuApp/Kotatsu/assets/85187197/602c1548-4701-4f26-9b2b-111a874f441b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by felo1** [comment]
This option is a deal breaker honestly. To me personally it's either Kotatsu for the functional sync or Mihon for auto downloads, and I'm more prone to device switching than reading on the go.

**Comment by Tareq4322** [comment]
tachiyomisy now supports sync. or you can use its fork called "komikku" which has a lot more feature than tachiyomi sy. also both of them supports sync and auto download
