### ISSUE TITLE
A graphical issue with the Webtoon reader mode

### ISSUE THREAD

**Issue by RandomParacodes** [KotatsuApp/Kotatsu#604]
### Brief summary

Occasionally, whenever transitioning to a new page, the mentioned reader mode freaks out and joins the two pages at random points. A swiping moment later, it fixes itself.

For me, this issue was reproducable on two mangas I've tried. And it happens constantly throughout the reading experience. I've also tried force stopping the app and reopening it. The issue was still reproducable.

https://github.com/KotatsuApp/Kotatsu/assets/84495683/db5a6208-84ac-4aa0-8e3c-46c67a0fa4a2

### Steps to reproduce

1. Open a manga designed for a Webtoon experience (easier to notice)
2. Swipe through a couple first pages until encounter issur

### Kotatsu version

6.5.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by RandomParacodes** [comment]
As of v6.6, the issue has not been resolved.

**Comment by nahhhbody** [comment]
I figured out how to fix this. The "Reduce memory consumption (beta)" seems to be causing the problem. Toggling it off in the reader settings has resolved the issue for me.
