### ISSUE TITLE
Add MyReading Manga as manga source 

### ISSUE THREAD

**Issue by ValentinOrient** [KotatsuApp/Kotatsu#623]
### Describe your suggested feature

Hello, I really like your app. It's wonderfully designed and light :) 
In the source list I didn't find MyReading Manga :/
And with a quick search I don't find any issues mentioning it.
https://myreadingmanga.info/
Can it be added into the app ?? Please 🥺

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
this is not a parser repo
