### ISSUE TITLE
"Failed to connect to" on Android 10

### ISSUE THREAD

**Issue by CyberDenner** [KotatsuApp/Kotatsu#626]
### Brief summary

All sources display "Failed to connect to..." error message when on Wi-Fi (and sometimes on mobile networks too)

It's working normally on Android 13, it looks like something specific to Android 10

![kotat_2024-01](https://github.com/KotatsuApp/Kotatsu/assets/146398551/3e7951c6-a29f-403d-9c25-4d8e848f7178)

### Steps to reproduce

1. Reinstall the app (in my tests the problem started after reinstall)
2. Explore different manga sources using mobile networks
3. Switch from mobile data to Wi-Fi
4. Explore different manga sources, but via wireless networks

### Kotatsu version

6.6.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
I think your isp is blocking mangadex

**Comment by CyberDenner** [comment]
It's not a problem with mangadex, this is happening with all sources (and only on my phone with Android 10)

**Comment by ztimms73** [comment]
my bad

**Comment by ztimms73** [comment]
Can you please check this?
https://kotatsu.app/manuals/guides/troubleshooting/common-issues/#advanced-errors

**Comment by CyberDenner** [comment]
I think I discovered the real problem.

The issue appears to be related to some setting in an android firewall application, so it probably wasn't a kotatsu issue.
