### ISSUE TITLE
Search in teamxnovel source not work

### ISSUE THREAD

**Issue by AhmedSamir899** [KotatsuApp/Kotatsu#631]
### Brief summary

when i search in teamxnovel source it show all manhwa not search

### Steps to reproduce

when search in it show results

### Kotatsu version

6.6.1

### Android version

13.0

### Device

redmi note 10s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
