### ISSUE TITLE
Add Original Language Filter on MangaDex Source

### ISSUE THREAD

**Issue by BudakPolitik** [KotatsuApp/Kotatsu#632]
### Describe your suggested feature

Hello guys, may I add a little suggestion to current MangaDex source. I want to filter the search by Original Language of the result but it seems like it's still not possible in Kotatsu. The Original Language Filter is a feature on Mangadex site, so I think it's quite feasible to add it to Kotatsu. 

![image](https://github.com/KotatsuApp/Kotatsu/assets/66526592/6a30be9e-3753-49a2-8007-ff0dc46671ac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
suggestions for parsers are accepted in the kotatsu-parsers repository
