### ISSUE TITLE
Ability to Change manga covers or thumbnails

### ISSUE THREAD

**Issue by GGgoBRO** [KotatsuApp/Kotatsu#635]
### Describe your suggested feature

It's simple. Just the ability to change the covers of manga either by a cover stored in local storage or any page of the manga (Just like tachi). 
It helps to change any Low quality covers or change to a latest one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by i-wavebyte** [comment]
i have pretty much the same request as some mangas have either a low quality or a broken thumbnail

**Comment by TWnight** [comment]
I was thinking the same thing and was going to open a feature request about it but I saw yours

**Comment by ztimms73** [comment]
Duplicate of #416
