### ISSUE TITLE
Mass Mark chapters/manga as read

### ISSUE THREAD

**Issue by Pleasefix2** [KotatsuApp/Kotatsu#637]
### Describe your suggested feature

I'm not sure if this has been suggested or not, but nothing came up when I searched. If it is a duplicate I apologize. The ability to mass mark multiple chapters as read would be very helpful. Also, the ability to click on multiple manga from the favorites screen and mark all their chapters as read at the same time (much like the "mass favorites" feature)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by perara-chen** [comment]
I believe this is a must have feature for kotatus.

**Comment by ztimms73** [comment]
https://github.com/KotatsuApp/Kotatsu/commit/627cf73d7226bdd1391519dc241d1884a9e52ce9
