### ISSUE TITLE
Page turn with volume keys

### ISSUE THREAD

**Issue by ziaa-xyz** [KotatsuApp/Kotatsu#639]
### Describe your suggested feature

self explanatory ,but, it feels a lot more comfortable for me when page turning with volume keys. It’s the only feature I miss after switching from Tachiyomi. Basically, volume up=previous page and volume down=next page

Option to invert volume keys (also in Tachiyomi) would be nice for landscape viewing, though I may be asking too much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Check reader settings
![Screenshot_20240111-092817](https://github.com/KotatsuApp/Kotatsu/assets/61558546/f98b418b-98ea-4cac-906d-968e79660c18)
