### ISSUE TITLE
Manga Migration

### ISSUE THREAD

**Issue by KraXen72** [KotatsuApp/Kotatsu#660]
### Describe your suggested feature

Allow a manga to be migrated to a different source.
**Reason:**
If a source dies, or one is unhappy with image quality, missing chapters, etc, they can migrate the manga.
Migration carries over progress, bookmarks, tracking, etc. and prompts user if they want to delete downloaded chapters (since other source likely has a different chapter naming scheme)
**Workflow:**
1. User hits `Migrate` button in manga detail
2. Selects which sources to search / search in all sources
3. the manga title will be searched in the sources
4. User selects the best candidate for migration. Can preview chapters beforehand to check image quality, etc.
5. User confirms migration. Old manga is removed from library and data is transfered to the new entry.
   
 This feature is inspired by Tachiyomi. for more details, check the app or one of it's forks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Already implemented 
On details screen press Three dots menu -> Alternatives
