### ISSUE TITLE
Continue reading button in library

### ISSUE THREAD

**Issue by KraXen72** [KotatsuApp/Kotatsu#665]
### Describe your suggested feature

Please add an option to show a 'continue reading' button straight in the library, that directly opens the viewer, so user doesen't have to go to manga detail. This button could be on top of the percentage circle. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
There are no "Library" section in Kotatsu. Such button present in the History section

**Comment by KraXen72** [comment]
Sorry i meant the 'faourites tab', and even in the history, there is no per-manga continue button, only continue last read manga. i meant a per-manga continue button.
