### ISSUE TITLE
Read duration statistics

### ISSUE THREAD

**Issue by KraXen72** [KotatsuApp/Kotatsu#672]
### Describe your suggested feature

It would be nice if kotatsu kept track of how much a) each day and b) overall did user read of which manga, for statistics purposes :3
Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Statistic is planned at v7

**Comment by KraXen72** [comment]
i see this has been implemented! thanks!
