### ISSUE TITLE
Tracking (mangaupdates // Kitsu)

### ISSUE THREAD

**Issue by umerraja786** [KotatsuApp/Kotatsu#683]
### Describe your suggested feature

Can you please add mangaupdates and kitsu tracking on the app Especially mangaupdates

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MeteorKLINT** [comment]
A similar question is asked here #360

**Comment by umerraja786** [comment]
> A similar question is asked here #360

Will you be adding those tracking or is it not possible

**Comment by umerraja786** [comment]
> A similar question is asked here #360

@MeteorKLINT will you adding those tracking ot is it not possible

**Comment by MeteorKLINT** [comment]
@umerraja786, I am not a developer, but I desire this feature too. My hope is by making the connections here and there to make this request more present.

**Comment by umerraja786** [comment]
> @umerraja786, I am not a developer, but I desire this feature too. My hope is by making the connections here and there to make this request more present.

@MeteorKLINT OK thanks any way I hope they do it soon
