### ISSUE TITLE
Hide extra scans in lectortmo

### ISSUE THREAD

**Issue by MakuSensei** [KotatsuApp/Kotatsu#697]
### Describe your suggested feature

![Screenshot_20240121-125521](https://github.com/KotatsuApp/Kotatsu/assets/16900914/391cd6e2-2d4a-45e4-8cbb-23b3a2720c8b)
Hello, I would like it to be possible to hide the extra scans, since they double the number of chapters, making it more difficult to read. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Open ticket in parsers repo
