### ISSUE TITLE
Automatic bookmarks / Memorizing pages

### ISSUE THREAD

**Issue by Absolit123** [KotatsuApp/Kotatsu#698]
### Describe your suggested feature

Add a function to remember pages in the chapter where you stopped reading. Otherwise, when you open a chapter, you have to re-search for the page you stopped on while reading, and bookmarks are not convenient. They are not always convenient and it is possible to use

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
To do this, there is a Continue button on the History screen and a Continue button on the manga information screen. Also make sure you have the Incognito and Exclude NSFW manga from history options turned off
