### ISSUE TITLE
Autoscroll bug. 

### ISSUE THREAD

**Issue by nahhhbody** [KotatsuApp/Kotatsu#700]
### Brief summary

• The autoscroll doesn't load the pages correctly every few pages, causing the top half to be truncated.

### Steps to reproduce

_Steps to reproduce:_
1. Turn on autoscroll.
2. The bug will happen after a few pages (reading in webtoon mode.)
3. The page won't load correctly/will stay cut-off unless you manually swipe back up on the reader. 

_Note:_
- The chapter I'm reading is downloaded on my device in the video. 
- I tried this on my phone and in an emulator and the same bug happens.

https://github.com/KotatsuApp/Kotatsu/assets/87543555/f3cd104e-2fc8-4a25-ae32-6260167683cc 

### Kotatsu version

Version 6.6.5

### Android version

- Android 9 & Android 13

### Device

Vivo Y21T & Samsung S21 (Emulator)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by RandomParacodes** [comment]
This is an issue which I have also brought up some time ago too!
It's an issue with the Webtoon reader mode as a whole.

https://github.com/KotatsuApp/Kotatsu/issues/604

**Comment by nahhhbody** [comment]
I marked this as complete since I found out how to fix the issue.
