### ISSUE TITLE
Sorting order - Last Read

### ISSUE THREAD

**Issue by aminoginji** [KotatsuApp/Kotatsu#705]
### Describe your suggested feature

Add a new sorting order under list options for last read. Would sort your manga based on last read in history

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
![Screenshot_20240124-082831](https://github.com/KotatsuApp/Kotatsu/assets/61558546/e0176c59-6690-4f91-9de3-c835702ea5ef)
Three dots -> List options

**Comment by aminoginji** [comment]
![Screenshot_20240124_004712_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/1223153/58daa71b-0b21-4415-88d1-92d3571ecd08)
I guess I should have specified in favorite's not history
