### ISSUE TITLE
Can't connect to MangaDex 

### ISSUE THREAD

**Issue by FraFrau7** [KotatsuApp/Kotatsu#706]
### Brief summary

Hello, I was using without issue the MangaDex source but suddenly it disconnected and I can't use it anymore. I have the most recent build and I'm not really sure if the problem is connected with the fact that I live in Italy, where MangaDex doesn't work. But it doesn't make sense, since in the beginning it was working fine. 

### Kotatsu version

6.6.5

### Android version

13.0

### Device

OnePlus 8t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
>  If this is an issue with a parser, I should be opening an issue in the parsers repository.
