### ISSUE TITLE
Kotatsu not showing images from bato 

### ISSUE THREAD

**Issue by erickpetern** [KotatsuApp/Kotatsu#718]
### Brief summary

Can not generate image list when reading bato manga please help try down grading and up grading still the same issue

![Screenshot_20240129-170820](https://github.com/KotatsuApp/Kotatsu/assets/130223774/f7b34896-0ab8-4eb3-81c1-a8e529b96eee)
![Screenshot_20240129-170802](https://github.com/KotatsuApp/Kotatsu/assets/130223774/e146c689-235d-4505-a6e1-cd7dff94c106)

### Kotatsu version

Version 6.

### Android version

11

### Device

Infinix hot 10 and Sony ax2 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> Version 6.
version what?

**Comment by ztimms73** [comment]
oh, I'm blind

> If this is an issue with a parser, I should be opening an issue in the parsers repository.

closing
