### ISSUE TITLE
imade 0 out of index

### ISSUE THREAD

**Issue by spidersonfire** [KotatsuApp/Kotatsu#725]
### Brief summary

im not the best with tecchnical things but ive been trying to read manwhas and i keep getting this pop up, and no chapters. ive tried reinstalling and updating the app but im not sure what else to do
![Screenshot_20240131_081733_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/158293536/c6645488-1bc5-4011-8692-92c190517478)

### Kotatsu version

6.6.6

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
1. Should be reported in the parsers repository
2. Duplicate
3. Already fixed, wait for the next release

**Comment by spidersonfire** [comment]
im sorry, where would i find the parsers? ive tried looking but i cant find it
