### ISSUE TITLE
Index 0 out of range [0..0)

### ISSUE THREAD

**Issue by Solandis** [KotatsuApp/Kotatsu#728]
### Brief summary

When trying to read or download manga from bato.to source I always get this pop up. Other sources are fine as far as Ive checked, only this seems to be affected by the bug.
![Screenshot_20240201_100753_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/113169398/96b74830-b864-4a7b-a352-56c7a5b1432a)

### Kotatsu version

6.6.6

### Android version

13

### Device

Samsung Galaxy A05s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
