### ISSUE TITLE
Tracking issue Myanimelist

### ISSUE THREAD

**Issue by ZellFk** [KotatsuApp/Kotatsu#729]
### Brief summary

After the latest updates the tracking from MAL broke, whenever I try adding the tracking on any manga an error occur (on version 6.6.6 it showed a java error) now on 6.6.8 we have this error below. (the tracking is logged on properly, I even redid the login on the tracker to validate but the issue still persists)

![Screenshot_20240201_101130_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/20177708/27027c83-7457-46cf-bc22-648222f232da)

### Kotatsu version

6.6.8

### Android version

14

### Device

Samsung Galaxy S24 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
![301354775-394d0654-fc97-4b57-99f5-4934cd652f6d](https://github.com/KotatsuApp/Kotatsu/assets/61558546/82ce2c4b-2e0d-4aae-aff9-7aee9d38b7ca)
