### ISSUE TITLE
Paged vertical mode

### ISSUE THREAD

**Issue by demonic-avenger** [KotatsuApp/Kotatsu#733]
### Describe your suggested feature

Please add a paged vertical mode. Its like the webtoon mode, but instead of being continuous, it appears as paged. Meaning you just scroll up or down pages

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
already implemented and we're testing this stuff, wait for major update
