### ISSUE TITLE
Blacklist "cloudflare sources" from suggestions

### ISSUE THREAD

**Issue by airisama019** [KotatsuApp/Kotatsu#735]
### Describe your suggested feature

Doing it once is okay but it keeps asking every day for the same sources and it's getting annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Vaktik** [comment]
I have the same issue man, it's Hella annoying

**Comment by ztimms73** [comment]
just disable "CAPTCHA required" notification in system settings
