### ISSUE TITLE
Manhwa pages not working

### ISSUE THREAD

**Issue by Mura36** [KotatsuApp/Kotatsu#736]
### Brief summary

Bow blade the spirit from the source manhastro is not working,

The error is image format not supported 

I am really sorry for my bad English 

### Steps to reproduce

![Screenshot_20240202-213732](https://github.com/KotatsuApp/Kotatsu/assets/158642395/7d48735f-6a28-4230-a640-7edc988a7b13)
![Screenshot_20240202-213727](https://github.com/KotatsuApp/Kotatsu/assets/158642395/2dcad108-8745-43be-aa65-ac1c123040ef)

### Kotatsu version

6.6.8

### Android version

11

### Device

Moto g8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).
