### ISSUE TITLE
Retain original title for nhentai 

### ISSUE THREAD

**Issue by Laplace9** [KotatsuApp/Kotatsu#744]
### Describe your suggested feature

When I download from nhentai, the app only saves the manga title and discards the translator group name and author name. This means that I only get an incomplete title. Let's take this as an example: [Zonda] Kenkyuubu Saishuuwa (COMIC Mugen Tensei 2023-01) [English] [Digital]. The app will only grab "Kenkyuubu Saishuuwa" and not [Zonda] Kenkyuubu Saishuuwa (COMIC Mugen Tensei 2023-01) [English] [Digital].cbz.

Interestingly, this problem does not occur on tachiyomi.

Please look into this matter. I want to retain original title without missing anything. 

P. S. I don't know if this count as feature request or a bug since I don't know if you created the manga downloader with what I said in mind. 

Hope this helps. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Should be opened in kotatsu-parsers
