### ISSUE TITLE
Sorting with Latest Update for Manga4life

### ISSUE THREAD

**Issue by opatua** [KotatsuApp/Kotatsu#745]
### Describe your suggested feature

Currently, with the manga4life source, we can only sort by name. It would be better to have a sort with the latest update too.
This feature better makes it general I believe most of the sources can be sorted by the updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Shadow573** [comment]
Same, I would like it if manga4life had a sorting order as well, since I use that site the most.

**Comment by ztimms73** [comment]
open issue in kotatsu-parsers repo
