### ISSUE TITLE
Suggestions are not working.

### ISSUE THREAD

**Issue by kisatti007** [KotatsuApp/Kotatsu#749]
### Brief summary

I have zero Genderswap Yaoi Villainess BL Boylove Shoujo(G) and any of these kind of mangas in my history nor my favourites, and i also have these tags in the exclude option, but for some reason i only get these kind of mangas in the suggestions.

### Kotatsu version

6.6.8

### Android version

14

### Device

Samsung Galaxy Z Fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Unfortunately filtering by genres does not work if source does not provide genres information in list
