### ISSUE TITLE
New feature and new parser

### ISSUE THREAD

**Issue by Styd-ispansky** [KotatsuApp/Kotatsu#750]
### Describe your suggested feature

Hello, I would like to suggest a new feature. It would be wonderful that when reading manga was a function to cut off the white fields on which there is no text at the top, bottom and sides, and that the picture was full. And I would like to ask to add a new parser for Russian-speaking users "mangabuff". There faster add chapters and their number is more. I will be grateful if you add.

Здравствуйте, хотела бы предложить новую функцию. Было бы чудесно, чтобы при чтении манги была функция обрезания белых полей на которых нет текста сверху, снизу и по бокам, и чтобы картинка была полная. И хотелось бы попросить добавить новый парсер для русскоязычных пользователей "mangabuff". Там быстрее добавляют главы и их количество больше. Буду благодарна, если добавите.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Duplicate of #326 and parser-specific issues should be opened in kotatsu-parsers repo
