### ISSUE TITLE
Reading time over estimation

### ISSUE THREAD

**Issue by RandomParacodes** [KotatsuApp/Kotatsu#756]
### Brief summary

This might seem like a nitpick, but the actual and estimated reading time will fluctuate differently from each others by a huge gap if it were to be calculated by the way utilized as of now.

### Steps to reproduce

I've read a manga (Kawaii Kanojo-chan for reference) with a time estimate of 1 hour and 36 minutes. But after done reading, the time only amounted to about 17 minutes.
This is because even though the manga features 29 chapters; in each of the chapters, there was only 4 pages. 2 for the extras.

Meanwhile, another manga I've read to test the theory (The Woman Who Messes With My Emotions) has an estimated reading time of 49 minutes, but I spent 1 hour and 27 minutes to read the entire manga; which features 15 chapters and 16 pages for each chapters.

### Kotatsu version

6.7

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
The calculation is based on the average number of pages in a manga (20 pages), the average reading time per page (10 seconds) and multiplied by the number of chapters. Estimated reading time is not based on user data and how fast they read and how many pages are in their series

**Comment by RandomParacodes** [comment]
![Screenshot_20240212-011450.jpg](https://github.com/KotatsuApp/Kotatsu/assets/84495683/5a33e95d-365b-4199-8ced-ad862a1e4bbf)
Here's one of the manga I've just read. The estimate is said to be 1 hour and 36 minutes. If I'm not hallucinating, that is.

Following the formula, we have appox. 5 pages average in the manga. Taking the 29 chapters number, we get this: 5 * 10 * 29=1450 seconds of approximated reading time.

Converting that into minutes, we have approximately 24 minutes of reading time. I'm not sure if I've done my math wrong or not.

**Comment by ztimms73** [comment]
yes, but if 20 * 10 * 29, that equals 5800
![image](https://github.com/KotatsuApp/Kotatsu/assets/61558546/77cda067-2643-498b-95ef-e255bf689b6e)

Check the estimated read time calculation code here, we're planning make an approximate reading time using local data analysis based on the speed of reading and the number of pages in chapters
