### ISSUE TITLE
Sort search results by number of chapters

### ISSUE THREAD

**Issue by storm546** [KotatsuApp/Kotatsu#768]
### Describe your suggested feature

I propose adding the option to sort the search results by number of chapters currently available. This would help with the fact that there are tones of sources for a manga that have a different number of chapters uploaded, so this option could save time if you could choose from the sources with most chapters uploaded instead of looking through a number of sources, or not realizing that other sources have more chapters and waiting for something that is already there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
It is not possible, information about chapters is not available in lists
