### ISSUE TITLE
Add option for grid mode in chapter list

### ISSUE THREAD

**Issue by jsericksk** [KotatsuApp/Kotatsu#769]
### Describe your suggested feature

I would really appreciate having an option to switch between list view and a grid mode for chapters, displaying only chapter numbers when in grid mode. Most of the time, I don't care about the title, description, or date of the chapters, so having a list with all these details to scroll through becomes a bit inconvenient.

I've already implemented this in a fork and can make a pull request, but I'd like to know if it could be a built-in feature of the app or if it's out of the question.

Below is a demo of how the app looks in [my implementation](https://github.com/jsericksk/Kotatsu/commit/9aeaf15346fa1f2765b2da48289043d05aae4ccd):

https://github.com/KotatsuApp/Kotatsu/assets/36176569/116c9ef0-8479-417e-9898-77e91d32e47b

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
I suppose grid view UI have to be a bit tuned, however the concept is ok, could you please create a PR?
