### ISSUE TITLE
Tracking read progress via Anilist raises error "Field 'SaveMediaListEntry' argument 'progress' requires type int

### ISSUE THREAD

**Issue by EthanZeigler** [KotatsuApp/Kotatsu#787]
### Brief summary

![Screenshot_20240223-100219](https://github.com/KotatsuApp/Kotatsu/assets/9123320/cabbeb5f-cbd5-44c3-a0dc-f1c3abf0df81)

### Steps to reproduce

1. Enable Anilist integrations and sign in
2. Open an in-progress read manga
3. Tap kebab menu
4. Tap 'Tracking'
5. Select the relevant manga source
6. Tap 'Done'

**Expected**:

Tracking enables successfully

**Actual**:

Toast appears with message `Field "SaveMediaListEntry" argument "progress" requires type Int, found 18.0` 

### Kotatsu version

6.6.8

### Android version

14

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Already fixed in 892f95a7a60e9778aeab82ca88a060c1ce11cf71, should work fine at v6.7+
