### ISSUE TITLE
Can't open sync service

### ISSUE THREAD

**Issue by akomalifour** [KotatsuApp/Kotatsu#789]
### Brief summary

can't open sync service always closes itself

### Steps to reproduce

1.setting 2.service 3.synchronization

### Kotatsu version

6.7.2

### Android version

7

### Device

Xiaomi Redmi 5A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Looks like Xiaomi-specific issue, try to open it via system settings

**Comment by akomalifour** [comment]
> Looks like Xiaomi-specific issue, try to open it via system settings

thanks
