### ISSUE TITLE
Adding new sources

### ISSUE THREAD

**Issue by Bdran4** [KotatsuApp/Kotatsu#795]
### Describe your suggested feature

This app is crazy good !!
I hope if GMANGA will be source added 
It would be amazing. 
And thank you for the hard work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by kyoyacchi** [comment]
You can open a issue on parser repository for source requests not here 😆
https://github.com/KotatsuApp/kotatsu-parsers

**Comment by Bdran4** [comment]
Sorry 😅 
First time using github
