### ISSUE TITLE
Luscious Extention suggestion

### ISSUE THREAD

**Issue by Indeciteful** [KotatsuApp/Kotatsu#808]
### Describe your suggested feature

Hi, I really like Luscious website https://members.luscious.net/accounts/login/?next=/
It was a great extension on Tachiyomi and I'd love to see it added to Kotatsu.
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
open an issue in kotatsu-parsers if the source request does not exist yet
