### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by FariBeki** [KotatsuApp/Kotatsu#819]
### Brief summary

Problemas no captcha, ele fica em loop, e n carrega a fonte

### Steps to reproduce

![Screenshot_20240316-114556_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/137515839/55de4a89-4e6a-4d8a-ac26-f8e16891e8db)

### Kotatsu version

6.7.5

### Android version

11

### Device

A10s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by airisama019** [comment]
ja tentou instalar o webview beta?

**Comment by airisama019** [comment]
![photo_2024-03-16_17-25-26](https://github.com/KotatsuApp/Kotatsu/assets/155326638/75dcb998-9a6e-42d2-8150-42937d82d4c1)

parece problema no kotatsu msm

funciona no navegador

**Comment by Koitharu** [comment]
Has been fixed in [v6.8](https://github.com/KotatsuApp/Kotatsu/releases/tag/v6.8)
