### ISSUE TITLE
Cant read ComicK manga

### ISSUE THREAD

**Issue by vexar0** [KotatsuApp/Kotatsu#825]
### Brief summary

App shows a Java error when trying to open a ComicK manga, cannot be read
![Screenshot_20240319_154847_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/117410135/c22d1ed7-a4ac-4ad0-a4dc-32cfb69533d9)

https://github.com/KotatsuApp/Kotatsu/assets/117410135/a5076d32-7d3b-4e95-89aa-507816f556f0

https://github.com/KotatsuApp/Kotatsu/assets/117410135/f0811b1c-9538-4369-a82a-538b9054b900

### Steps to reproduce

1. Choose ComicK manga source
2. Open a manga

### Kotatsu version

6.7.5

### Android version

14.0

### Device

Galaxy S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
