### ISSUE TITLE
solve captcha issue

### ISSUE THREAD

**Issue by akomalifour** [KotatsuApp/Kotatsu#837]
### Brief summary

blank no captcha resolve
![Screenshot_2024-04-03-12-22-22-089_org koitharu kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/95312948/c075c967-7e20-4513-9f26-452923e80139)

### Steps to reproduce

1.open extension nhentai.net 2.click solve captcha button 3.page blank

### Kotatsu version

6.8.3

### Android version

7

### Device

Xiaomi Redmi 5A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
