### ISSUE TITLE
download button

### ISSUE THREAD

**Issue by Seyien** [KotatsuApp/Kotatsu#844]
### Describe your suggested feature

Can you add a download button on the side of the undownloaded episode tiles?

In terms of user experience, there will be people who long click and don't realize that the episode is available for download, or people who realize too late.

Worst case, they might want to download it with the download button on the side instead of long-clicking.

![image0](https://github.com/KotatsuApp/Kotatsu/assets/110932038/af2f4287-6dbc-44cd-b42d-2b70f5fa74d0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Adding chapters one-by-one to the download queue is not a good idea.
You can select multiple chapters and download it all at in one task instead

**Comment by Seyien** [comment]
> Adding chapters one-by-one to the download queue is not a good idea. You can select multiple chapters and download it all at in one task instead

actually the idea was that the user would be able to explore the feature to download the episode.

As far as I can see, this has been done quite well with the serie detail page v7.0-rc2.

I appreciate very much what you have done.
