### ISSUE TITLE
PIN man/ga/hwa/hua in home screen

### ISSUE THREAD

**Issue by reconxr** [KotatsuApp/Kotatsu#847]
### Describe your suggested feature

So I hope if we can PIN man/ga/hwa/hua without PIN limitation in home screen
I hope you add this feature in the next update ^^

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
You can create a shortcut for manga on the home screen via Details screen -> three dots menu -> Create shortcut

**Comment by reconxr** [comment]
I mean to PIN in app home screen it would be very useful to me and anyone else

**Comment by ztimms73** [comment]
what do you mean by home screen?

**Comment by reconxr** [comment]
In history page I mean it would be amazing if I can pin mangas to easily know what am I reading

**Comment by galpt** [comment]
@reconxr is probably asking for a way/feature to quickly know what's the last manga he's reading, exactly right after he opens up Kotatsu app again.
 
He wants Kotatsu to show not just 1 manga he's reading last time, but make it so users can select more than 1 manga, pin them, and show them like this:
 
 **Your pinned manga**
 1. Manga one
 2. Manga two
 3. ...
 
Well, @reconxr should try to explain it better with some examples if possible, just in case I explained it wrong.

**Comment by ztimms73** [comment]
My solution to not bloat the app with unnecessary features:
1. Make the Favorites screen section first on the list in the bottom navigation bar
2. Make the category Pinned and put it at the top of the list of categories
3. Add manga to this category
4. ???
5. PROFIT
