### ISSUE TITLE
Baozimh error.: java.security.cert.certpathvalidatorexception trust anchor for certification

### ISSUE THREAD

**Issue by kevinwenyu** [KotatsuApp/Kotatsu#850]
### Brief summary

i installed the app on android 8.0 tablet. when i open Baozimh, it's shows the error : "java.security.cert.certpathvalidatorexception trust anchor for certification".

![image](https://github.com/KotatsuApp/Kotatsu/assets/34227344/5e566c75-3390-477a-ab19-56cd7a8a3c88)

what i did to solve the problem:
1. change the site domain to "webmota.com"in source setting, then it can show the searching page. but can not read commic.
2. i tried to install on my phone (android 14) it works well

### Steps to reproduce

just open the source and you will find the error promt.

### Kotatsu version

6.8.3

### Android version

8.0

### Device

Samsung Tab A 2016

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by kevinwenyu** [comment]
for other source works fine, but Baozimh is not. i'm not sure it's a parser issue or not.

**Comment by ztimms73** [comment]
https://kotatsu.app/manuals/guides/troubleshooting/common-issues/#javasecuritycertcertpathvalidatorexception
