### ISSUE TITLE
Add MangaWorld source

### ISSUE THREAD

**Issue by FrancescoXD** [KotatsuApp/Kotatsu#852]
### Describe your suggested feature

MangaWorld.ac is the best Italian manga source. It has a lot of translated manga compared to other websites.
Is there a way to add it?
Thank you.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
wrong repo
