### ISSUE TITLE
source bug

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/Kotatsu#855]
### Brief summary

For the source komikzoid.id, you can't open the manga in the application,but it will work if you open it with a browser and for the Sektekomik source you can't download the manga because of an invalid error

### Kotatsu version

6.8.3

### Android version

13.0

### Device

redmi note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
wrong repo
