### ISSUE TITLE
This site won't load any pictures

### ISSUE THREAD

**Issue by Reignleigh24** [KotatsuApp/Kotatsu#858]
### Brief summary

I wanted to re-read the manhwa named eleceed in toomanhua source since it's the only site that uploads in full chapter per episodes with no cut scenes in it. But suddenly it won't load any pictures from it no matter how many times i refresh it even tho my kotatsu app is in the latest update. Please bring it back as i have many manhwa's on that sute that i've been saved.

### Steps to reproduce

![Screenshot_20240428_133447_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/168010424/9a892dc9-2d8f-499c-bc52-b0582471b51b)

![Screenshot_20240428_133501_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/168010424/f79e03b5-8517-410e-b9db-7fe44f6df971)

![Screenshot_20240428_133511_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/168010424/68fd5776-ac99-4a29-930a-636306652514)

![Screenshot_20240428_133520_Samsung Internet](https://github.com/KotatsuApp/Kotatsu/assets/168010424/19d81842-3c02-498b-84a2-575237919f0f)

### Kotatsu version

6.8.1

### Android version

14

### Device

Samsung Flip 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
