### ISSUE TITLE
Too many requests,try again later

### ISSUE THREAD

**Issue by Thenikkel** [KotatsuApp/Kotatsu#865]
### Brief summary

One of the manga sources just tells me this and when I press again it keeps telling me the same and when I come back later it stills me the same or it shows me some manga but when i scroll it tells me it again.ive tries deleting cookies and it doesn't do anything.

### Steps to reproduce

I press manga source then it tells me it 

### Kotatsu version

6.8.3

### Android version

11

### Device

TCL 20 xe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
