### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Chellyph14** [KotatsuApp/Kotatsu#867]
### Brief summary

It's been a while since I requested to update fonts and add new fonts. Please update the Portuguese language application. thanks .

### Kotatsu version

6.8.3

### Android version

Android 11

### Device

Samsung Galaxy A6 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Fonts?

**Comment by Chellyph14** [comment]
the extensions I requested to update and add.

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
