### ISSUE TITLE
Add Categoris in kotatsu

### ISSUE THREAD

**Issue by WEPOXS** [KotatsuApp/Kotatsu#868]
### Describe your suggested feature

![Screenshot_20240506_170604_Mihon](https://github.com/KotatsuApp/Kotatsu/assets/146017577/3a1116d2-5970-4584-ac74-cb02c417a2b6)
![Screenshot_20240506_171043_Mihon](https://github.com/KotatsuApp/Kotatsu/assets/146017577/60f6706d-eb0a-447c-b405-757a86e46522)
Later there will be several options for where to put it 

Sourch: mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
https://kotatsu.app/manuals/guides/categories/
