### ISSUE TITLE
Download Chapters not showing while Offline 

### ISSUE THREAD

**Issue by mogodo** [KotatsuApp/Kotatsu#871]
### Brief summary

I can't see the chapter I downloaded while I'm Offline 

### Steps to reproduce

Exemple :
1. Open a manga on your Library by clicking it
2.  Download any chapter 
3. Go back to your Library 
4. Disable your wifi or mobile data
5. Re-open the manga

### Kotatsu version

7.0-rc2

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by AndreasStgm** [comment]
Got the same issue. Bumping to hopefully increase priority.

**Comment by ztimms73** [comment]
@AndreasStgm are you using the latest 7.0 release?

**Comment by ztimms73** [comment]
nvm, this behavior should be fixed
https://github.com/KotatsuApp/Kotatsu/commit/9b658cf0b8cd3ac08f1cf5b98d0d65f0e0bdf90b

**Comment by AndreasStgm** [comment]
@ztimms73 I am using 7.0. But if it's fixed for the upcoming release I guess I'm good :)
