### ISSUE TITLE
A button to go to in-app download page

### ISSUE THREAD

**Issue by ShinoIro** [KotatsuApp/Kotatsu#875]
### Describe your suggested feature

It's really a little way to see the download page, it's either on a notification bar or pnce you just start downloading..
at first it was okay to just go to the notification to see the download page, but it's difficult once the app is hidden..
I am asking if it isn't too much to add a button to go to the download page.. 
the location is up to the devs, i do have suggestion for it to be placed to the "3 dot button"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
![изображение](https://github.com/KotatsuApp/Kotatsu/assets/8948226/fb691beb-3242-4fd9-90fa-244474e1f5c4)

**Comment by ShinoIro** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/8948226/329863115-fb691beb-3242-4fd9-90fa-244474e1f5c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzA2MDMsIm5iZiI6MTcxNTUzMDMwMywicGF0aCI6Ii84OTQ4MjI2LzMyOTg2MzExNS1mYjY5MWJlYi0zMjQyLTRmZDktOTBmYS0yNDQ0NzRlMWY1YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTYxMTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVmNzZmMWRmMDA4NmNkMzVhYmIyNmE2M2EzNGQyYmQ3ZDVkZWNmMjMzNWUyNTI1YTY0OTUzMDBkOTY5OTk2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.efWnsi5L1HJdarv60dQHvj9vYwoQfIlfyMAiqiKIvYI)

silly me, couldnt't see that big button haha, thank you
