### ISSUE TITLE
Bug sinensistoon network error 

### ISSUE THREAD

**Issue by CintiaM1907** [KotatsuApp/Kotatsu#884]
### Brief summary

Source sinensistoon.com is not working, cannot pass CAPTCHA. Another is also the same problem cerisescan.

### Steps to reproduce

![Screenshot_20240516-220558](https://github.com/KotatsuApp/Kotatsu/assets/167935120/ae6c1db6-3511-4c60-b00c-421f77a188d6)

### Kotatsu version

7.0.1

### Android version

13

### Device

Samsung A03 core 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
