### ISSUE TITLE
Content not found.

### ISSUE THREAD

**Issue by Resimaa** [KotatsuApp/Kotatsu#887]
### Brief summary

I cant read chapters because of this.
![Screenshot_20240519_105031_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/143012426/cb7b5099-960b-408b-855a-0ed3ff745357)

### Steps to reproduce

1. Go to manga
2. Opan a chapter
3. Content missing

### Kotatsu version

7.0.1

### Android version

Android 14

### Device

Samsung galaxy a53 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> If this is an issue with a parser, I should be opening an issue in the parsers repository.
