### ISSUE TITLE
Migration Search Through Disabled sources 

### ISSUE THREAD

**Issue by mogodo** [KotatsuApp/Kotatsu#891]
### Brief summary

When I'm searching for alternatives sources for a manga with the "Alternatives" option in the manga screen it search through all sources even disabled onces witch make the process way too slow.

### Steps to reproduce

1. Open a manga in your Library 
2. Click on the three dots in the top right to show more options 
3. Click on "Alternatives" in the option list

### Kotatsu version

7.0.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by mogodo** [comment]
> Enabled sources are processed first so search through disabled sources isn't slow down the search

Sorry I made a mistake here, It was manga that was not available in the majority of my enabled sources witch give me the sensation that it was just searching through all the app manga sources in the alphabetical order.

**Comment by Koitharu** [comment]
The priority is:
1. Enabled sources with same language
2. Enabled sources with other languages
3. Disabled sources same language
4. Disabled sources other languages

**Comment by mogodo** [comment]
Understood
