### ISSUE TITLE
Can't read certain mangas

### ISSUE THREAD

**Issue by Windmather** [KotatsuApp/Kotatsu#898]
### Brief summary

I can't read chapters of certain mangas and it said No value for hentai

### Kotatsu version

7.1.1

### Android version

13.0

### Device

Tecno Pova 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by IzuUuUuUUUu** [comment]
I happen to have the same issue as you do and i dont really know what to do

**Comment by wijiisaiah** [comment]
Ran into the same issue, but only on manga I was already reading. New stuff was fine.

As a work around, I went to settings and cleared my cache and app storage. Then I was able to reopen the mangas I was reading. Lost progress though so suggest backing up your data first.

**Comment by IzuUuUuUUUu** [comment]
wijiisaiah i did the same thing but its still screwed up any other way u could think of on how to fix it?

**Comment by DPilat-Dev** [comment]
I have this issue on the comik source

**Comment by SKazehaya** [comment]
I too have the exact same issue, but it only happens on a few mangas from 'ComiK' source.

**Comment by myusernameiscool** [comment]
same with comick source
