### ISSUE TITLE
ComicK not working

### ISSUE THREAD

**Issue by Jinxergirl** [KotatsuApp/Kotatsu#907]
### Brief summary

Manga/Manhwa through ComicK manga source don't load chapters and say "No value for hentai" at the bottom. All I do i click on the webtoon as normal. This started happening today.

### Steps to reproduce

![Screenshot_20240527_170433_Kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/170981795/1eab60e0-5c4f-42d9-ad66-181292cb479c)

### Kotatsu version

6.8.3

### Android version

13.0

### Device

Samsung S20+ 5G

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by NagaYZ** [comment]
Update your app

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.

**Comment by IdkAnythin07** [comment]
clear your cookies from sources it'll fix
