### ISSUE TITLE
add mass migrate feature , to help with slow scanlations

### ISSUE THREAD

**Issue by Weebguild** [KotatsuApp/Kotatsu#908]
### Describe your suggested feature

a significant number of tachiyomi users miss the mass migrate feature which helped us to shift to other scanlations quickly , in bulk if we faced slow updates on a title , from one source

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by JIINNN01** [comment]
There's a reason it was removed from mihon and other forks you know. It leads to sources banning/breaking extensions.

**Comment by Weebguild** [comment]
> There's a reason it was removed from mihon and other forks you know. It leads to sources banning/breaking extensions.

i didn't know that one , it was seriously helpful though and as far as i remember only tachiSY removed it , J2K still had it running , and mihons beta  versions up until the latest 16.0 updates all had this feature, but it is true that send warning messages right now to prevent the same
