### ISSUE TITLE
please add a new jp manga source.

### ISSUE THREAD

**Issue by afat123** [KotatsuApp/Kotatsu#911]
### Describe your suggested feature

like the title suggest, need a new manga source for jp language.
the source website is called = https://raw1001.net

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment]
wrong repo
