### ISSUE TITLE
Add , chapter added date

### ISSUE THREAD

**Issue by Weebguild** [KotatsuApp/Kotatsu#913]
### Describe your suggested feature

There should be some way to view when a specific chapter has been released, this can help in identifying which chapter it is without opening it , as there are multiple cases where different sources have the same chapter titled with a different chapter number , especially (COMICK and MANGADEX , sometimes even MANGATOP).

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment]
wrong repo
