### ISSUE TITLE
Imported local manga files don't have favorites restored

### ISSUE THREAD

**Issue by CyberDenner** [KotatsuApp/Kotatsu#921]
### Brief summary

Imported manga favorites are not being restored from backup. 

(this issue is **only** happening with imported files)

### Steps to reproduce

1. Import mangas/hqs
2. Favorite it
3. Backup and restore
4. Import the same files again

### Kotatsu version

7.1.2

### Android version

Android 14

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Cannot reproduce, could you please provide a screencast(video)?

**Comment by CyberDenner** [comment]
I think I discovered the real problem. It's just that my backup file was still from before 7.1.2 (it was 7.1 probably but I'm not sure).

In local storage section it was shown as if the manga was not in any favorites while in playlists it was shown as if the related file had not been found. But when using the backup files generated in version 7.1.2, I couldn’t replicate the same bug.
