### ISSUE TITLE
Migration doesnt carry over tracking information

### ISSUE THREAD

**Issue by MariusAlbrecht** [KotatsuApp/Kotatsu#930]
### Brief summary

title + it results in duplicate tracking entries which can make for weird cahnges in the tracking provider if the 2 entries arent the same (doesnt break anything tho as far as I've seen)

### Steps to reproduce

1. add tracking to a specific source
2. migrate to another source
3. have to add tracking again

### Kotatsu version

7.2

### Android version

12

### Device

Oneplus 7Pro

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Do you mean tracking like Anilist or MAL, right?

**Comment by MariusAlbrecht** [comment]
exactly, yes
