### ISSUE TITLE
Не работают сторонние источники манги,. 

### ISSUE THREAD

**Issue by Nik1991z** [KotatsuApp/Kotatsu#931]
### Brief summary

Например в источнике hentailib.me пишет что нету глав. 

### Steps to reproduce

https://github.com/KotatsuApp/Kotatsu/assets/172526409/47bb0d1e-db64-46e1-a9d2-249cddf169dd

### Kotatsu version

7.2

### Android version

14

### Device

 Realme GT Neo 3T 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Nik1991z** [comment]
Хотя я зашёл через свою учётную запись, и скромно нету глав, пишет ошибка, решите эту проблему пожалуйста.

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
