### ISSUE TITLE
List of things y'all should add. This would improve the app greatly.

### ISSUE THREAD

**Issue by Fuzzythegoatq** [KotatsuApp/Kotatsu#932]
### Describe your suggested feature

![Screenshot_2024-06-10-16-24-10-373](https://github.com/KotatsuApp/Kotatsu/assets/124460008/1a04d92f-41c4-4001-8b44-0ece909a3a7e) 
![Screenshot_2024-06-10-16-25-11-721](https://github.com/KotatsuApp/Kotatsu/assets/124460008/a2ca65b7-6da5-4ac6-813b-aba431f9c813)
![Screenshot_2024-06-10-16-22-06-670](https://github.com/KotatsuApp/Kotatsu/assets/124460008/8a729470-4c01-4fc1-9ff7-0d3fef87f469)
![Screenshot_2024-06-12-15-37-43-114](https://github.com/KotatsuApp/Kotatsu/assets/124460008/c6759331-2b1a-464c-911a-c3618f9db75e)

Add Quick Reader, And badges
![Screenshot_2024-06-10-16-28-01-282](https://github.com/KotatsuApp/Kotatsu/assets/124460008/06ea740e-49a0-474a-9466-55e403640455) And Add show number of items
![Screenshot_2024-06-12-12-02-49-773](https://github.com/KotatsuApp/Kotatsu/assets/124460008/be49e338-0dbe-4dd1-a185-c96da31e2c67) Also add edit info
![Screenshot_2024-06-12-12-03-07-231](https://github.com/KotatsuApp/Kotatsu/assets/124460008/6af23086-07db-4736-8b52-1bf899c99b72)

![Screenshot_2024-06-12-15-32-43-515](https://github.com/KotatsuApp/Kotatsu/assets/124460008/5caa9f9a-1990-43f1-8e92-28a3fd50cbd4)

Add repos support ( Would be cool cuz I'm trying to put keiyoushi in Kotatsu)

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment]
It is a bad idea to offer many features in one ticket. Create a new ticket for each feature, except for the feature to support unofficial extension repositories for Tachiyomi. We won't do it, it calls into question the point of the parser library that we specifically made for Kotatsu. Along with this, installing Tachiyomi extensions and supporting them in Kotatsu will never happen
