### ISSUE TITLE
Auto-download chapter option

### ISSUE THREAD

**Issue by YrzqArk** [KotatsuApp/Kotatsu#955]
### Auto-download new chapter

Hello,

This feature will work easily, you can check or not an option who allow the app to Auto-download new chapter to read later.

This feature can let us to read a scan in the networkless environnement.

Thank~.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Tareq4322** [comment]
I've requested this feature a long time ago in github. Hope this post will get the attention of the dev
