### ISSUE TITLE
Manga Sources Pin on the Bottom

### ISSUE THREAD

**Issue by BoneMarrow10** [KotatsuApp/Kotatsu#957]
### Brief summary

Why are the pinned manga sources at the bottom? Including when I'm searching for something. It also seems there's no option to change it on the manga source settings menu.

### Steps to reproduce

1. Pin any manga sources
2. The manga sources automatically move to the bottom
3. Try use the search feature to search some manga
4. The manga you're searching for from the pinned source will appear at the bottom most list. Making you have to wait the other sources to load before finding the sources you pinned.

### Kotatsu version

7.3

### Android version

12

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Cannot reproduce, could you please provide a screen recording?

**Comment by BoneMarrow10** [comment]
The pinned manga source works as intended now
