### ISSUE TITLE
Downloaded chapters will be deleted once removed from favorites

### ISSUE THREAD

**Issue by daniruGG** [KotatsuApp/Kotatsu#973]
### Describe your suggested feature

As the title says. 

I'd like to request this feature so I do not have to manually delete the downloaded chapters before removing it from favorite categories.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
Downloaded chapters will be deleted only in case you delete it explicitly.
Favorites and Downloaded are unrelated features, you can download manga what is not in favorites and vise versa
