### ISSUE TITLE
Koneksi jaringan terblokir

### ISSUE THREAD

**Issue by Riobasker** [KotatsuApp/Kotatsu#978]
### Brief summary

Koneksi jaringan saya di blokir sehingga saya tidak dapat membaca komik kesukaan saya, mohon dibuka blokir nya. 

### Steps to reproduce

![Screenshot_2024-07-21-20-15-01-018_org koitharu kotatsu](https://github.com/user-attachments/assets/e6c08533-3869-4b03-9efb-be024a41bcd6)

### Kotatsu version

7.3

### Android version

9 PKQ1.181203.001

### Device

Redmi S2 M180E6G

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
