### ISSUE TITLE
Please allow reimporting unzipped, changed and rezipped backup files

### ISSUE THREAD

**Issue by vkmi** [KotatsuApp/Kotatsu#983]
### Describe your suggested feature

I was really happy to see that kotatsu unzipped backup file was a human readable json file.
I needed to merge two backups from two devices, manually edited the backups and then found out it was impossible to reimport the edited backup, after zipping it.

I was surprised to see that even simply unzipping and rezipping the backup file made it impossible to reimport the backup file.

Please allow reimporting edited backup files.
If you're worried about people breaking something, you could put a warning.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by Koitharu** [comment]
Need some more info:
What does the "impossible to reimport" mean?
If possible it would be nice if you provide the file

**Comment by vkmi** [comment]
It was my error, as I was rezipping the folder wrong (zipping the extracted folder, instead of zipping the group of files).

Sorry for wasting your time.
