### ISSUE TITLE
Issue with manga source

### ISSUE THREAD

**Issue by anonymousloger** [KotatsuApp/Kotatsu#984]
### Brief summary

AsuraScans is unavailable. It says "Nothing found" when we select it from the manga source list.

It would be very helpful if we could have a feature to check which sources are still active and which are inactive.

### Kotatsu version

7.3

### Android version

14

### Device

Samsung Galaxy S23 Ultra 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
> This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.
