### ISSUE TITLE
Incognito issue 

### ISSUE THREAD

**Issue by Anshuman2259** [KotatsuApp/Kotatsu#989]
### Brief summary

I turned off incognito mode and it's still showing on the progress bar of manga that incognito is on 

### Steps to reproduce

Turn on incognito 
Turn off incognito 
Open any manga and in the read button it will not show the chapter you are on but instead it will show incognito mode
![Screenshot_2024-07-25-16-05-42-27](https://github.com/user-attachments/assets/4a598b3f-190e-46c3-ade1-cd9ee7794e72)
![Screenshot_2024-07-25-16-05-50-44](https://github.com/user-attachments/assets/4b26ee59-f1a3-4603-b53c-ce5e856f40d5)

### Kotatsu version

7.3

### Android version

9.0

### Device

Oppo A31

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
This manga is marked as 18+ and looks like you enabled the option to ignore NSFW manga reading progress in settings

**Comment by Anshuman2259** [comment]
> This manga is marked as 18+ and looks like you enabled the option to ignore NSFW manga reading progress in settings

Tried to turn off the setting but nothing changed

**Comment by Anshuman2259** [comment]
I clear the cache and it worked
